### ISSUE TITLE
Public API or DB dumps

### ISSUE THREAD

**Issue by q3k** [ctftime/ctftime.org#10]
A nice feature would be some way to programatically access ctftime.org data without web scraping. Preferably a public API to retrieve team/event data, or if that's not possible then periodic database dumps of the public data.

**Comment by q3k** [comment]
Possible uses:

 - notification about upcoming CTFs to teams
 - live widgets on teams' sites (current standing, last CTFs played)
 - metadata for teams' CTF systems (organizers, contact, website, current standing)
 - extra data processing by external entities (experimental ranking algorithms, ...)
 - ...

**Comment by gynvael** [comment]
The upcoming CTFs is already present via RSS: https://ctftime.org/event/list/upcoming/rss/
+1 on the rest of the things, especially the live widgets idea ;)

**Comment by kyprizel** [comment]
have you checked https://ctftime.org/api/ ?
