### ISSUE TITLE
Clarification about team merging

### ISSUE THREAD

**Issue by draane** [ctftime/ctftime.org#100]
Hello,
it's not clear if "You can merge teams not later than 2 weeks after the event finished" refers to the very first event or to any event.
So if I create a new team and compete in 2 events with it, can I merge it with my other team within 2 weeks from the second event?
Thanks

**Comment by kyprizel** [comment]
Yes, it should be not more than 2 weeks after "alias" team participated. There was an ugly bug which can lead to error in merging ability check if you had problems - please try now.
