### ISSUE TITLE
Unlink to writeups from my team pages

### ISSUE THREAD

**Issue by howmuch515** [ctftime/ctftime.org#103]
My writeups aren't listed in my team page(https://ctftime.org/team/51588) and can't edit these (ex: https://ctftime.org/writeup/13758, https://ctftime.org/writeup/8856 ..etc).

Please fix link and edit permission.

**Comment by Pharisaeus** [comment]
It seems that's a global issue, not only yours.

**Comment by kyprizel** [comment]
Can you please provide more details? What is the exact problem?

**Comment by Pharisaeus** [comment]
@kyprizel team page shows only few latest writeups, not all of them. Example: https://ctftime.org/team/5152#writeup_list

You can click on "load more" a few times but it runs out at 

0CTF/TCTF 2019 Quals | Ghost pepper | read writeup
-- | -- | --

Whereas there are hundres writeups more by this team. First writeup (chronologically) not included is https://ctftime.org/task/7456 and nothing older than 2019 is visible.

**Comment by kyprizel** [comment]
Nice catch! Fixed a nasty bug which prevented old writeups to be displayed in many places.
