### ISSUE TITLE
SECCON CTF 2019 Rating not carried from previous year.

### ISSUE THREAD

**Issue by UTCoordinator** [ctftime/ctftime.org#113]
Hello,

Just wanted to bring it to your notice. SECCON CTF is an annual Japanese CTF. In 2018, you can check their event https://ctftime.org/event/683 . The future rating weight says 46.80

However, in this year https://ctftime.org/event/799 , the future and current rating weight is 0.00

Shouldn't it be 46.80 Current Weight instead of? Can this be fixed ?

**Comment by kyprizel** [comment]
Should be fixed by now
