### ISSUE TITLE
Team with such name already exists

### ISSUE THREAD

**Issue by olivatooo** [ctftime/ctftime.org#114]
I can't add an alias to my team: `Shingeki No Chikungunya`

We played under:
`ShingekiNoChikungunya`
`Shingeki_No_Chikungunya`

https://ctftime.org/team/104937

And when I try to add an alias it say: "team already exists"

EDIT: 

Shingeki_No_Chikungunya -> https://ctftime.org/team/105001

ShingekiNoChikungunya -> https://ctftime.org/team/105258

**Comment by olivatooo** [comment]
Can't merge teams via form

**Comment by kyprizel** [comment]
Please, send more details.

**Comment by olivatooo** [comment]
I played 3 CTFs under 3 different names (the names I listed above), but after I've played I cannot set the alias, because CTF Time created the teams! I only created the team named `Shingeki No Chikungunya`  and CTF Time automatically created the others after I played. So I can't get my points, because I can't set the aliases. I already requested team merge but no one responded me

**Comment by kyprizel** [comment]
Have you create team merge request?

**Comment by olivatooo** [comment]
Yeah... 18 Nov to be more precise

**Comment by congtrung2k1** [comment]
Is this issue solved? Have same problems here, 
I am the 1st member and have sent request "im in the team" 3 months ago and still nothing.

**Comment by olivatooo** [comment]
yeah, in my case my teams were merged

**Comment by congtrung2k1** [comment]
Do you know how to request to join in already existed team, i have sent request 5 times, but still can't. I'm the first

**Comment by olivatooo** [comment]
If some time have passed, you can't join anymore I think
