### ISSUE TITLE
Public voting not enabled

### ISSUE THREAD

**Issue by mr-96** [ctftime/ctftime.org#118]
Hello,

I'm wondering why public voting is disabled for our event (https://ctftime.org/event/905) that will take place on 30/11. I know that the event has not started yet, but usually there is "This event's weight is subject of public voting!" on the page also before the event.

Also I don't understand the logic in setting some on-site only events that does not require quals (such as https://ctftime.org/event/922) with public voting and other events without it.

Thanks!

**Comment by kyprizel** [comment]
There is clear restriction to onsite-only teams.

**Comment by mr-96** [comment]
The same restriction applies in the second link that I provided (and also in all the finals, even when organizers do not provide travel grants and prizes)
