### ISSUE TITLE
Voting weight not on event

### ISSUE THREAD

**Issue by theKidOfArcrania** [ctftime/ctftime.org#119]
Hi, our event that we are hosting: https://ctftime.org/event/948 is not showing an link for doing public voting for weight, but in comparison, this ctf from justCatTheFish: https://ctftime.org/event/943 has a a link for public voting. (both of them starts around the same time)

What is exactly the logic for determining whether if an event can be publicly voted on or not? I know that some reasons that underpin this question is (a) CTF is an onsite and/or restricted to certain teams/groups, or (b) it happens over a long span of time, which neither of these applies to our case?

**Comment by theKidOfArcrania** [comment]
any response to this @kyprizel ?

**Comment by kyprizel** [comment]
The event is too small for rating.

**Comment by theKidOfArcrania** [comment]
Hmm what do you exactly mean by too small... can this be negotiated or not?
