### ISSUE TITLE
TAMUctf is listed as invite-only, but it is academic, open to all

### ISSUE THREAD

**Issue by addisoncrump** [ctftime/ctftime.org#126]
We attempted to reach out over the feedback form last week with no response. Would you please mark TAMUctf as academic, not invite-only? I can provide proof that I am the development lead for this CTF as necessary.

**Comment by kyprizel** [comment]
fixed

**Comment by addisoncrump** [comment]
Ah, my mistake -- I had misunderstood the academic listing to be "academically run", not "academically restricted". Anyone can play in our CTF!

Would the most appropriate listing be open? If so, would you please mark it as such?
