### ISSUE TITLE
Delete teams

### ISSUE THREAD

**Issue by nadrojisk** [ctftime/ctftime.org#127]
Hello, for some reason we have many duplicate teams for our CTF team. I cannot merge them as the events they were in happened a long time ago. I'm not sure as to why the duplicates we ever made because we usually use the same team name for competitions.

We have "au-ethical-hacking-club" "Auburn CTF" "Auburn EHC" "auctf" and "AUEHC". The only team that should be there is "AUEHC". I cannot seem to find a way to disband teams on the main site. Is there a way to do this? Thanks

**Comment by kyprizel** [comment]
No, you can not delete teams.
