### ISSUE TITLE
Feature Request: sitemap

### ISSUE THREAD

**Issue by psifertex** [ctftime/ctftime.org#13]
After seeing two other comments that are mostly due to people not knowing features exist (one of which I knew about, the other of which was new to me too), I think a sitemap would help people find things on the site better. Even better, create an automated site map, but also have a reorganization of the menu up top to allow people to find things they want from there. I'm probably missing a lot, but here's a quick stab at what that might look like: 

- EVENTS
    - Upcoming events
    - Archives
    - Calendar
- TEAMS
    - Current List
    - Maybe archived years here? Dunno
- CTF PLAYERS
    - New to CTF
    - Find a team (dating)
    - Upcoming Events
    - Other resources
- CTF ORGANIZERS
    - For-Organizers (maybe update to have a new 'submit ctf form instead of requiring it be done via email)
    - API
    - Json-scoreboard-feed
    - Code (sample code in various languages for interacting with ctftime, maybe)
- SITE INFO
    - FAQ
    - About
    - Contact Us
    - Issues (link to github)
    - Rating Information
- Signin/Profile

**Comment by kyprizel** [comment]
Changed menu a bit.
