### ISSUE TITLE
Messed up CTF end time

### ISSUE THREAD

**Issue by nadrojisk** [ctftime/ctftime.org#134]
Hi! I have an event next week, April 3rd. I messed up the end time. It is supposed to end April 5th 11 PM CST which I put down wrong. I believe the correct UTC is 4 AM April 6th. Can this be corrected? sorry for putting it in wrong

**Comment by kyprizel** [comment]
1. Please, tell the exact event id
2. Use email

**Comment by nadrojisk** [comment]
@kyprizel 

1. I believe it is event ID 1020, should be AUCTF 2020

2. Will do in the future thanks!

**Comment by nadrojisk** [comment]
Turns out I really cannot do times.... We messed up our start time too... It should start at 8:00 AM CST, we have it at 3:00 UTC which is not correct. It should be 13:00 UTC for 8:00 AM CST.... So sorry! @kyprizel
