### ISSUE TITLE
Cannot Login Anymore

### ISSUE THREAD

**Issue by JakeT24** [ctftime/ctftime.org#135]
Hello, been trying to login to CTF for a while now but I can't because I made the account in 2016 and can't remember what social media platform I used to login. Furthermore, I've deleted all of those platforms, meaning I couldn't try to login anyway to see which one it was. I know the email and I still get emails from CTF, but I can't login. I couldn't find an email or phone number to contact CTF and no response from the feedback form. The username on the account would be JakeT24, help would be much appreciated!

**Comment by kyprizel** [comment]
Check your email.

**Comment by mauricesvp** [comment]
I have the same problem, my account name is maoam. Would appreciate any help.

(Perhaps there should be a contact form for non-logged in user as well?)

**Comment by kyprizel** [comment]
Use your twitter acc.

**Comment by kyprizel** [comment]
https://ctftime.org/amnesia/

**Comment by mauricesvp** [comment]
@kyprizel I have deleted the associated Twitter account, thats why I cant log in. Anything I can do?

**Comment by kyprizel** [comment]
Please, login with some new account and send username to info@ctftime.org

**Comment by ghost** [comment]
Hi!

Unfortunately, I have the same problem. My account name is Seelkadoom (https://ctftime.org/user/64980). I registered it via Google Account which I've lost permanently.

Any help, please? @kyprizel 

Cheers!
