### ISSUE TITLE
OAuth API documentation

### ISSUE THREAD

**Issue by nsychev** [ctftime/ctftime.org#136]
From https://github.com/CTFd/CTFd/pull/1300 we know that CTFTime can be OAuth provider. Can you publish some documentation about it to make it possible to implement CTFTime authorization for other platforms?

**Comment by kyprizel** [comment]
All the required information is here:
https://ctftime.org/for-organizers/oauth/
It's standart OAuth flow (see links in the doc).

**Comment by kyprizel** [comment]
Any ideas what specifically should be added there?

**Comment by kyprizel** [comment]
ok, closing
