### ISSUE TITLE
Rating weight of 5 day CTF set to 0

### ISSUE THREAD

**Issue by kmh11** [ctftime/ctftime.org#137]
Hi! [ångstromCTF 2020](https://ctftime.org/event/982) recently had its rating weight set to 0. Looking at other CTFs that recently changed to 0, I assume this has to do with our length, but the [information page](https://ctftime.org/for-organizers/) says:

> If your event lasts more than 5 days - there will be no rating points for the event.

ångstromCTF lasts exactly 5 days, which is _not_ more than 5 days. Would it be possible to get this fixed? Thanks.

Edit: I noticed that [ångstromCTF 2019](https://ctftime.org/event/774) has the same issue now as well.

**Comment by kyprizel** [comment]
Yeah, that's a mistake. Should be fixed.
