### ISSUE TITLE
Voting page comments limited to 140 chars

### ISSUE THREAD

**Issue by XeR** [ctftime/ctftime.org#140]
Comments on the voting page are limited to 140 characters.

This results in people posting long comments on the CTF page and linking them on the voting page. See Redford's, theKidOfArcrania's, XeR's and terjanq's comments of [TAMUctf 2020](https://ctftime.org/event/1009/weight) for example.

This limit should be lifted, or, if it is by design, limit the textarea's max length to inform voters that their comment is limited in size.

**Comment by kyprizel** [comment]
That's intended behavior.
.

**Comment by XeR** [comment]
What about limiting the textarea length to inform new voters that this field is size-limited ?

**Comment by kyprizel** [comment]
Done.
