### ISSUE TITLE
Removing event from team's " Participated in CTF events" list

### ISSUE THREAD

**Issue by bl4de** [ctftime/ctftime.org#141]
Hi Guys,

For AUCTF 2020 event someone registered a team with the same name as the one I use for last 5 years during online CTF events. 

The result from AUCTF 2020 was added to my 2020 "Participated in CTF events" list, with the place and points scored. I **did not participate** in this CTF, I don't want to take a credit for someone's else score/points and I want to remove it from the list.

Is there any way to manage this?
How events scoreboard are matched against CTFtime.org team profile? By name only?
Stay Safe Guys,

Regards,

bl4de
https://ctftime.org/team/16701

**Comment by kyprizel** [comment]
There is no way to fix it - CTFtime just aggregated scoreboard and can't check if your team name was used by you or someone else.
