### ISSUE TITLE
Change event window from 12 to 18 months in CTF scoring system

### ISSUE THREAD

**Issue by briskly** [ctftime/ctftime.org#142]
I am a CTFZone organizer. We have been doing our CTF for 3 years. Last CTFZone final was in November 2018. We have decided to move our CTF from autumn to spring, because of many reasons. The first and the main reason is that we became DEFCON qualifier this year, and we would like to make our ctf more comfortable for defcon participants (visa and travelling consideration) so we moved our quals and finals to comply with defcon ctf cycle. That’s why we made quals in December and finals in April.
Formally we missed year 2019. But in fact, we just postponed our event for several months. According to ctftime rules the rating of our CTF is going to be 0 this year. 
There are external factors which can move your CTF dates:
1.Defcon cycle which have period starting from September  
2.Visa troubles, epidemical situation etc which can easily move events.
3. Ctf finals are usually bond with conferences and ctf organizers doesn’t have influence on the dates of this conferences (+-2 month is a normal situation)

That is why I would like to propose to expand the period of CTF ranking to 18 month since last event.

**Comment by kyprizel** [comment]
Sounds reasonable, especially with all this COVID stuff.
https://twitter.com/CTFtime/status/1250117849055707136
