### ISSUE TITLE
OAuth authorization page displays incorrect scopes with `team` only

### ISSUE THREAD

**Issue by ginkoid** [ctftime/ctftime.org#143]
When specifying just the `team` scope, the authorization page displays text indicative of the `profile team` scope:
> Event organizers will get access to your username, email and chosen team name.

However, the application does not actually get access to profile information. As a result of this bug, users who might want to keep their email private might wrongly decide to not authorize the OAuth application.

**Comment by kyprizel** [comment]
Thanks, fixed.
