### ISSUE TITLE
OAuth authorization page is not responsive

### ISSUE THREAD

**Issue by ginkoid** [ctftime/ctftime.org#144]
On desktop devices, the authorization page has to be opened in either a full screen popup or a top frame redirect to prevent scrollbars. Scrollbars are unavoidable on mobile devices at the moment.

Because OAuth authorization pages are frequently opened in popups, it makes sense for them to scale to many different sizes so that the popup can be as small and focused as possible.

**Comment by kyprizel** [comment]
Can you check it now, please?

**Comment by ginkoid** [comment]
It works great. Thanks!
