### ISSUE TITLE
CTF quality and rating/weight systems

### ISSUE THREAD

**Issue by mr-96** [ctftime/ctftime.org#145]
Hi, I'm opening this to (hopefully) discuss something to improve the current rating system on CTFTime.

I basically noticed that a lot of introductory-level ctfs are being run in the last weeks, and that they are voted 25 from newbie/random teams that simply want to increase their score on CTFTime. With the current scoring system, if you want to go on the top of the leaderboard is more convenient to play easy ctfs, even if their weight is lower. 

For example: getting P50 at 36C3 (weight 63) gives 4.4 points, getting P50 at VirSecCon 2020 (weight 22) gives 15 points.

Maybe it's not the best example, but I think you're getting my point: it's easier for a newbie team to get 300/350 points at the end of the year than for a decent team that wants to play only high quality/difficulty ctfs.

I don't have a solution to this, but I think it would be interesting to discuss about how the scoring system and the weight system can be modified to avoid this.

**Comment by kyprizel** [comment]
Only 10 best results count.

**Comment by mr-96** [comment]
I don't see how this solves the problem. If I get the same points as the 1st classified team of the CTF I get exactly the weight points, do this 10 times and get 250. Maybe sometimes I'm even more lucky and get a good placement, so I take 35/40 points, basically I have 300 "free points" at the end of the year. Taking 10 top level CTFs and get 30 points each is not easy at all, especially for small teams.

**Comment by kyprizel** [comment]
Wellm that's not easy to get 35/45 points in CTFs with weight 25.

**Comment by mr-96** [comment]
Right, but this basically moves the problem to 250 points instead that 300/350. My point is that it's in general easier to get a decent amount of points from an easy ctf than from a difficult one, and also that in general difficult ctfs are rated lower because they are voted by top teams, while introductory ones are voted by random teams that simply want to increase their score.

**Comment by kyprizel** [comment]
That's why voting weight counts only for next year. If it's first-time run CTF I don't know what we can do here w/o manual moderation.

**Comment by mr-96** [comment]
This issue was in fact to discuss this. Maybe changing the "rating formula" can partially solve the issue, or introducing some algorithm related to the teams that played the ctf and not only to scoring and position. I am not saying that what you are doing now is wrong, I'm saying that maybe someone can come up with a decent idea to improve it.
