### ISSUE TITLE
'OK (not really, contact info@)' error

### ISSUE THREAD

**Issue by javinotfound** [ctftime/ctftime.org#146]
Hello.

I can't join a team.

Also, I can't delete my account and save my profile.

When I tried, this is the error that I got: 'OK (not really, contact info@)'

This account is recently created using GitHub. Maybe this problem only occurs with new accounts.

Could you check it?

**Comment by javinotfound** [comment]
Finally, I was able to join.

I will maintain this issue opened, so you can check it what happened.

**Comment by kyprizel** [comment]
That's intentional- you followed very specific action pattern which is used by spammers.
