### ISSUE TITLE
Fix mime types in email messages

### ISSUE THREAD

**Issue by kyprizel** [ctftime/ctftime.org#148]
Now both messages handled as html. Need to make them alternative.

**Comment by NilsIrl** [comment]
ctftime.org email (bad):
![image](https://user-images.githubusercontent.com/26231126/80498483-b0406800-8963-11ea-9161-830f0ce35df2.png)

github.com email (good):
![image](https://user-images.githubusercontent.com/26231126/80498550-c2220b00-8963-11ea-8693-ef3e3fc9555c.png)

**Comment by kyprizel** [comment]
Fixed.
