### ISSUE TITLE
CTF rating and weight voting is still ambiguous !

### ISSUE THREAD

**Issue by maroueneboubakri** [ctftime/ctftime.org#150]
Well, I attempted 2 CTFs (not sure if they are) the first is this 
https://ctftime.org/event/997
and the second one is this
https://ctftime.org/event/1023

My feedback is: both have the exact same tasks quality, same platform etc.

While we see that the first has voting enabled til 30pts despite its first year ! while voting is disabled on the second.

So if you think that the second is a shitty CTF I swear that the first is shitty also, and if you enabled voting on the second you should see the same exact feedback.

So either enable voting on both or disable on both.

Also I suggest to review CTF weight voting scheme. I agree that plenty of shitty CTF tend to have the same weight as historical CTFs and this due to max vote from "noteams".

Thanks
Maro

**Comment by kyprizel** [comment]
Voting was disabled for Guess CTF b/c it was mostly about guessing and was positioned as a joke.
For second CTF I don't know anything, so we use democracy to rate it - people can vote for event.
