### ISSUE TITLE
Writeups don't survive a team merge

### ISSUE THREAD

**Issue by NilsIrl** [ctftime/ctftime.org#151]
It's not possible to edit the writeups from before a team merge either.

**Comment by kyprizel** [comment]
Can you provide more details, please?

**Comment by NilsIrl** [comment]
Pwnzorz merged with FlagGrenade (to become FlagGrenade). I can't edit the writeups that were posted when the team was Pwnzorz and the writeups don't show up on the team page of FlagGrenade.

**Comment by kyprizel** [comment]
Thanks. Fixed.
