### ISSUE TITLE
Can't use account after editing information

### ISSUE THREAD

**Issue by Mandragorian** [ctftime/ctftime.org#152]
I created an account, then edited some of my personal info.

After that I can't use some of the functionality of this site, like further edit my info, request to join a team or delete my account. I couldn't even use the feedback form.

I get this reply in the browser

OK (not really, contact info@)

**Comment by kyprizel** [comment]
Please, provide more info.

**Comment by Mandragorian** [comment]
I authorized with github. Then I was presented with a page that had some personal info. I edited my username, first/last/name, and my country (i think).

After that when I try to use some functionality of the site I get "OK (not really, contact info@)" as a reply in the browser.

**Comment by kyprizel** [comment]
Clean your cookie.
