### ISSUE TITLE
Unable to sign in anymore

### ISSUE THREAD

**Issue by ghost** [ctftime/ctftime.org#155]
It seems I have no choice but to submit a new issue...

I made the account in September 2019 by using a Google Account. Unfortunately, I've lost the access to the Google Account permanently because I had the password generated in KeePass and I lost it due to my HDD failure (my fault that I forgot to create backup). There is no way for me to recover that account (no recovery options set), thus I am unable to login to CTFtime anymore.

My account name is Seelkadoom (https://ctftime.org/user/64980).

Any help, please?

**Comment by kyprizel** [comment]
Register a new one then send account details to info@ctftime.org.

**Comment by ghost** [comment]
Ok, I've registered the new account and sent its details via e-mail. But I have no response.

So, what's next?

**Comment by ghost** [comment]
@kyprizel, could you take a look on my e-mail, please? How long should I wait for the help yet?
