### ISSUE TITLE
Logged in with github, now whenever I click anything it says "OK (not really, contact info@)"

### ISSUE THREAD

**Issue by legndery** [ctftime/ctftime.org#157]
This is including bug reports. When I report Bug also, same error.

**Comment by kyprizel** [comment]
it's antispam, try to clean your cookies

**Comment by avarayr** [comment]
This issue still persists using Brave Browser. The temporary solution is to turn off the "guards" in the brave browser, and disable 3rd party cookie blocking for ctftime.

Hopefully maintainers will make the website compatible with the Brave Browser.
