### ISSUE TITLE
Unable to sign in anymore vol. 2

### ISSUE THREAD

**Issue by ghost** [ctftime/ctftime.org#158]
I didn't want to do this again, but I have no choice.

@kyprizel, I sent you the details of my new account via e-mail just as you'd directed me, but I haven't gotten any response in this matter by now.

I know this is all my fault but c'mon - couldn't you just delete the old account for me to be able to rename the new one? Or ask me for more info if you need?

How long do I have to wait for this? I really want to play CTFs again :(.

**Comment by GorlikItsMe** [comment]
I also have this problem. I clicking on team site "I'm in the team!" and "Join the team" button but only what happend is redirect to https://ctftime.org/profile and error 
" Specified invalid captcha, team does not exist or invite_only "
![image](https://user-images.githubusercontent.com/33355238/88386228-3c6dfa00-cdb0-11ea-8905-f108672f0bf5.png)

Team owner diable invites but i still cant join.

**Comment by GorlikItsMe** [comment]
Hi i find fix
They have error with grecaptacha

Execute in console in browser
`grecaptcha.ready(function() {
        grecaptcha.execute('6Lfl-uUUAAAAAFgA71MPRAPNGt8xQjV2C30BsoXT', {action: 'join'}).then(function(token) {
    document.querySelectorAll('input.django-recaptcha-hidden-field').forEach(function (value) {
        value.value = token;
    });
    return token;
})
    });`
and then try for me works
