### ISSUE TITLE
Created new team, accidently left - no way to join empty team

### ISSUE THREAD

**Issue by MaxXor** [ctftime/ctftime.org#159]
Hello, I created a new team, accidentally left it and it says on the team page `There is no registered members of this team. Click on "I'm in the team" - be the first.`. But there is no such link/button? Any way I can join the empty team again?

**Comment by kyprizel** [comment]
No there is not. Don't leave teams "accidently".

**Comment by MaxXor** [comment]
That's unfortunate... How about adding at least a confirmation before clicking that button?

**Comment by MaxXor** [comment]
Why does it mention `Click on "I'm in the team" - be the first.` when there is no way to join an empty team? It would be really kind to have some assistance?

**Comment by MaxXor** [comment]
Thank you very much! :+1: Have a great day.

**Comment by kyprizel** [comment]
I see now - there was no team leave confirmations on team management page, on profile one. Fixed.
