### ISSUE TITLE
Total points of my team are wrongly calculated

### ISSUE THREAD

**Issue by malladisiddu** [ctftime/ctftime.org#160]
I've noticed this issue with the summing up of CTF points today.  I've added all the points that we've scored this year to date, then I noticed that it was wrongly calculated by ctftime.org. According to ctftime.org we got >=105, when I added them manually I got >=144. I am attaching the excel sheet here for reference.
Team Name: [c0d3_h4cki05_](https://ctftime.org/team/72702)
[c0d3_h4cki05_.xlsx](https://github.com/ctftime/ctftime.org/files/4826947/c0d3_h4cki05_.xlsx)

**Comment by kyprizel** [comment]
Only best 10 results count.
