### ISSUE TITLE
Unable to create a new team.

### ISSUE THREAD

**Issue by javinotfound** [ctftime/ctftime.org#161]
The problem is clear. When I try to register a new team, it shows 'Team creation error' and nothing we can do.

Another members has tried too with same result.

Please, could you see what happens?

Thanks.

**Comment by pakosmith** [comment]
Faced the same problem. It's occurs because of you don't pass google recaptcha - it's not displayed due to an error in the js code

**Comment by GorlikItsMe** [comment]
Hi i find fix
They have error with grecaptacha

Execute in console in browser
`grecaptcha.ready(function() {
        grecaptcha.execute('6Lfl-uUUAAAAAFgA71MPRAPNGt8xQjV2C30BsoXT', {action: 'join'}).then(function(token) {
    document.querySelectorAll('input.django-recaptcha-hidden-field').forEach(function (value) {
        value.value = token;
    });
    return token;
})
    });`
and then try for me works

**Comment by javinotfound** [comment]
> grecaptcha.ready(function() { grecaptcha.execute('6Lfl-uUUAAAAAFgA71MPRAPNGt8xQjV2C30BsoXT', {action: 'join'}).then(function(token) { document.querySelectorAll('input.django-recaptcha-hidden-field').forEach(function (value) { value.value = token; }); return token; }) });

It works as temporary fix but I executed before this code in browser:

`/* PLEASE DO NOT COPY AND PASTE THIS CODE. */(function(){var w=window,C='___grecaptcha_cfg',cfg=w[C]=w[C]||{},N='grecaptcha';var gr=w[N]=w[N]||{};gr.ready=gr.ready||function(f){(cfg['fns']=cfg['fns']||[]).push(f);};(cfg['render']=cfg['render']||[]).push('6Lfl-uUUAAAAAFgA71MPRAPNGt8xQjV2C30BsoXT');w['__google_recaptcha_client']=true;var d=document,po=d.createElement('script');po.type='text/javascript';po.async=true;po.src='https://www.gstatic.com/recaptcha/releases/r8WWNwsCvXtk22_oRSVCCZx9/recaptcha__es.js';var e=d.querySelector('script[nonce]'),n=e&&(e['nonce']||e.getAttribute('nonce'));if(n){po.setAttribute('nonce',n);}var s=d.getElementsByTagName('script')[0];s.parentNode.insertBefore(po, s);})();`

It's the code of [JS API Recaptcha](https://www.google.com/recaptcha/api.js?render=6Lfl-uUUAAAAAFgA71MPRAPNGt8xQjV2C30BsoXT) that should be loaded before calls to grecaptcha

**Comment by kyprizel** [comment]
Thanks! Should be fixed now.

**Comment by panchitorrepiolin** [comment]
al entrar al servido cuando me voy a registrar me sale un error en el registro , intente mas tarde por que pasa eso y como lo soluciono ¿?
