### ISSUE TITLE
Contact Email Form Won't Send

### ISSUE THREAD

**Issue by TheNullSec** [ctftime/ctftime.org#162]

**Comment by TheNullSec** [comment]
So I believe there are some fields missing from the contact form. When I click submit i receive a 'This field is required error'. 

https://ctftime.org/feedback

![image](https://user-images.githubusercontent.com/57946518/88407942-c75bee00-cdca-11ea-8500-5b18e6d64d88.png)

**Comment by TheNullSec** [comment]
When I try this on my Kali machine I get a web page with the following text displayed: "OK (not really, contact info@)"

**Comment by kyprizel** [comment]
That was a problem with recaptcha integration. Fixed.
