### ISSUE TITLE
Wrong maximum weight for EKOPARTY CTF 2020

### ISSUE THREAD

**Issue by XeR** [ctftime/ctftime.org#164]
[EKOPARTY CTF 2020](https://ctftime.org/event/1137/weight)'s maximum weight is 100.
According to the [previous edition's weight](https://ctftime.org/ctf/121), this year's edition's maximum weight should be 25.

**Comment by sinfocol** [comment]
May we have a way to include other years weight? We are using the same platform, infrastructure, creative categories of challenges and we had too much effort invested, ekoparty events of other years have been well qualified, for external reasons it was not possible to integrate in the previous two years and from our point of view the calculation with the maximum of 25 points seems unfair. Thanks.

**Comment by Pharisaeus** [comment]
@sinfocol this sounds like a more general discussion about voting and CTF scoring so perhaps this is not the right place for that. Current rules are pretty clear, and current scores should be consistent with that.

I suggest you read through https://github.com/ctftime/ctftime.org/issues/40 and https://github.com/ctftime/ctftime.org/issues/61 first and decide if you want to start another discussion of this kind :)
