### ISSUE TITLE
Ambiguous sentences in "Send CTF details" Page

### ISSUE THREAD

**Issue by RaminAT** [ctftime/ctftime.org#168]
In this page:
https://ctftime.org/event/mail/
This sentence:
"After we approve you CTF management privileges — you'll need to submit event details by yourself."

Should be "After we approve **your** CTF management privileges — you'll need to submit event details by yourself."

And also in this section: "Is this CTF allowed for teamplay?"
The option to choose says "Individual" which is completely ambiguous. Should we check it if we allow team play or not? the option says "Individual" but the sentence doesn't match. And why is it asked anyway if Individual CTFs are not allowed for listing in ctftime?

**Comment by kyprizel** [comment]
Thanks, fixed.
