### ISSUE TITLE
Max team name length and max team alias length do not match

### ISSUE THREAD

**Issue by krzys-h** [ctftime/ctftime.org#169]
We recently participated in a CTF under a name `PredicateOrderHelperIteratorMapperSchemaListPolicyAnnotationPolicyAnnotationPrototypeTestsTemplateMapTemplateDispatcherInstanceModelPublisherPropertyPoolPropertyAnnotationPoolStubListenerVisitorAdapterStateMIMServiceAdapter` (223 characters) as a joke to see how much we could break the website layout, since their scoreboard system didn't seem to have a team name length limit. After the scoreboard was imported into ctftime, the name was truncated to 128 characters which is fair, since it's the maximum team name length ctftime allows. However, we noticed that the input fields in the "team aliases" section allow only a maximum of 64 characters - shouldn't they also go up to 128?

**Comment by kyprizel** [comment]
I don't see the reason.
