### ISSUE TITLE
Remove a member from the team

### ISSUE THREAD

**Issue by dhanvi** [ctftime/ctftime.org#17]
I wish if there is a way to remove members from the team, you might have accepted the people by mistakenly or if the member no longer fits in the team

**Comment by psifertex** [comment]
Or someone could have joined a team before you claimed it mistakenly. That happened to us and I was able to just email and ask for the change to happen, but I see your point. Still, getting the details done right could be tricky. This could also allow someone who joins a team to hijack it. There would probably have to be the concept of team captains versus regular members to differentiate who could remove members.

**Comment by dhanvi** [comment]
+1 for captain and normal user idea :+1:

**Comment by kyprizel** [comment]
How is the captain setting process is going to work? First who joined the team?
But what if that person isn't a captain or retired?

**Comment by psifertex** [comment]
You could default to the first-person who joined, but allow them to delegate multiple other captains.

Heck, maybe some teams would want to make /everyone/ a captain if they really trust everyone. Just make it clear that any time someone is a captain they are going to have the ability to do whatever to the team and don't complain if you make someone a captain who does something bad!

**Comment by kyprizel** [comment]
Can captain kick another captain? :) How will be captain status revoced?

**Comment by psifertex** [comment]
I'd say yes, and the answer is don't make someone a captain unless you trust them. :-)

Worst case, could email the same as is done now for team changes like that, but it would occur much less frequently.

**Comment by kyprizel** [comment]
I mean - kicking a member is not a problem, but returning a player back to team is harder.

**Comment by psifertex** [comment]
Maybe add a button to force a refresh of the team token? Then the captain could just kick someone and change the token. Then if someone wants to be joined back to the team, someone can just give them the new token. Really in most cases, the admin probably doesn't even need to reset the token -- only if the team member happened to log whatever the token was while they were still on the team some time in the last seven days.

**Comment by kyprizel** [comment]
Token is valid for 1 week.

**Comment by psifertex** [comment]
Right -- which is why if I kick someone off and they looked at a token before I did, I need to be able to reset any tokens valid for the last week. I don't know enough about the implementation to comment on how that might be done. Assuming the token is an encrypted time-stamp, possibly a random salt per-team that is able to be reset in such instances?

**Comment by kyprizel** [comment]
Yes, if we can enable kicking - need to change the schema a bit.

**Comment by dwendt** [comment]
If this is added, could it come with "team history"? It would be convenient to see: x joined team y 2013, x left team y 2014, x was kicked from team z 2015

perhaps a personal privacy setting.

**Comment by bl4de** [comment]
:+1: Good idea.
Maybe "kicking" is not the best term in all cases, however there should be an option to remove inactive members, eg. someone who does not play for the very long time.

**Comment by abdilahrf** [comment]
here #27 @kyprizel  : Added a "Leave" button in profile page, so now users can self dependently leave teams they joined.

i can't see that Leave button

**Comment by kyprizel** [comment]
Now 2 members can remove any other.
https://ctftime.org/faq/#kickmember
