### ISSUE TITLE
How to extend registration period?

### ISSUE THREAD

**Issue by RaminAT** [ctftime/ctftime.org#171]
There are many CTFs running simultaneously and we want to postpone our CTF for 48 hours. How to do this?

**Comment by kyprizel** [comment]
You need to send more exact details:
1. event id
2. new event start and finish name

**Comment by RaminAT** [comment]
Event id: 1167

Our announcement:
Due to many CTF competitions running simultaneously, we have extended the registration period for another 57 hours.
Thus RaziCTF 2020 will begin on October 26th at 5:30 UTC. 

So the new finish time is: October 28th at 5:30 UTC. 
Thanks.
