### ISSUE TITLE
Oauth secret is None

### ISSUE THREAD

**Issue by mateuszdrwal** [ctftime/ctftime.org#174]
So I want to try implementing ctftime oauth. Since we don't currently have another ctf up on ctftime I wanted to try using our [old ctf](https://ctftime.org/event/893/), but looking at the admin page the oauth secret is `None`. After i set the oauth endpoint to `http://localhost:8080/` it didn't change. The oauth authorization endpoint also returns `Invalid event or not configured` whatever i try. Here is my current testing authorization link:

https://oauth.ctftime.org/authorize?state=aaaaaaaaaaaaa&redirect_uri=http://localhost:8080/&scope=profile:read&client_id=893&response_type=code

What could be the issue here? Is maybe using an old event for testing not supported?

**Comment by kyprizel** [comment]
Using old events is not supported.

**Comment by mateuszdrwal** [comment]
Is there any other way to develop with ctftime oauth without having an upcomming ctf then? We aren't nearly ready to publish to ctftime but it would be great if i could still implement ctftime oauth in my ctf platform.

**Comment by kyprizel** [comment]
Let's discuss it via DM.
