### ISSUE TITLE
Event API doesn't provide the event icon

### ISSUE THREAD

**Issue by tsheinen** [ctftime/ctftime.org#175]
I have an application which needs the icon of an event but since the event api doesn't provide the icon link I need to visit the page and scrape it.  It's pretty achievable bc it doesn't really need to handle more than a few events a week but it feels like the event icon is something which should be part of the API so I wanted to mention it.

**Comment by kyprizel** [comment]
Can you check if current icon is good enough?

**Comment by tsheinen** [comment]
looks good!  thanks!
