### ISSUE TITLE
A team was automatically created on my name because I didn't have CTFTime.com account, now I cannot join the team it's pending for months

### ISSUE THREAD

**Issue by legndery** [ctftime/ctftime.org#176]
It said if I am the first member I will be joined automatically, it hasn't happened yet.

team name: legndery
user name: legndery

and this is me!

**Comment by izcatoriz** [comment]
I have had the same issue for months! My teammates and I are unable to join our team even though it appears as empty and it says the first member will join automatically. Our requests have been pending for months...

**Comment by legndery** [comment]
And no one replies from the main site as well, I tried to contact them multiple times using the contact form.

**Comment by izcatoriz** [comment]
Same...tried the contact form as well. Seems like they're not very active on Twitter either. Really don't want to give up on the team name but running out of ideas here.

**Comment by kyprizel** [comment]
Well, team legndery membership was approved. Another one -
