### ISSUE TITLE
Ctftime.org oauth provider doesn't work for certain states ({"message":"invalid state"})

### ISSUE THREAD

**Issue by Trolldemorted** [ctftime/ctftime.org#178]
Hey,

I already have filled in a form on ctftime but I am not sure whether it was submitted successfully, so I am opening an issue here.

Your OAuth2 endpoint returns `{"message":"invalid state"}` if the state is longer than a certain number of bytes, and our states apparently are. Could you increase the maximum length of the state?

**Comment by kyprizel** [comment]
try now

**Comment by Trolldemorted** [comment]
Did that, but `https://oauth.ctftime.org/authorize?client_id=1043&scope=team%3Aread&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%2Fauthorized&state=CfDJ8G93PB5gK1dHuT4wAt21M8kXEf_hu3TOpMyMq2T1FWZErEk-F4fVAhCahDGOCvPnMTch1GA8XyRK0xgTv-VMIawh2bAhztyjNK5RVBhDauwEmlhkerZwOeF5Ldi5Ww3MJ3ii7KDznJxrvYclny2kCEuJ80IqHPwnBqMO0h5DeEUvr97qTvlADnpQ85toSUrzyVgaRbpAaDuXXr9nR1R8nqZKBzh-6Ly2jwBQfa7zj6sDpTZR1xIfPP_InYuYCDA0W0PKjmpSY6K_TJESSjwt49A` is still printing `{"message":"invalid state"}`

**Comment by kyprizel** [comment]
and now?

**Comment by Trolldemorted** [comment]
`https://oauth.ctftime.org/authorize?client_id=1043&scope=team%3Aread&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%2Fauthorized&state=CfDJ8G93PB5gK1dHuT4wAt21M8nBPAhHwCVRIBhS3woVO7BEikK6exaseJA-wTlGXiim0TQvpOZKhVd1gUK0InCLOusNdQdfnXHV7saoO9TOJW9J1VhbKDaY0hFGGbpUiROE6e6gbiY6h_aPHCGwTiRGzp0KzMSG4aH3aeicbEtsmfwJlQywwdKtsFvIFx3yVUd_MHriqlfrluy6hzu2HZHypizZMCIRRhoEBZ2qWl_hB5Dllh810YZNjBZSjOk_F4h9TLqwwq0Joqcg0xiaplwTjeM` just gave me an `{"message":"invalid state"}`

**Comment by kyprizel** [comment]
loosed a regexp, try now please

**Comment by Trolldemorted** [comment]
Doesn't work :(

Btw you can just use the links I posted, they are still causing invalid state errors :)

**Comment by Trolldemorted** [comment]
Could it be you are not allowing dashes?

`https://oauth.ctftime.org/authorize?client_id=1043&scope=team%3Aread&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%2Fauthorized&state=CfDJ8G93PB5gK1dHuT4wAt21M8nBPAhHwCVRIBhS3woVO7BEikK6exaseJA-wTlGXiim0TQvpOZKhVd1gUK0InCLOusNdQdfnXHV7saoO9TOJW9J1VhbKDaY0hFGGbpUiROE6e6gbiY6h_aPHCGwTiRGzp0KzMSG4aH3aeicbEtsmfwJlQywwdKtsFvIFx3yVUd_MHriqlfrluy6hzu2HZHypizZMCIRRhoEBZ2qWl_hB5Dllh810YZNjBZSjOk_F4h9TLqwwq0Joqcg0xiaplwTjeM` is forbidden but `https://oauth.ctftime.org/authorize?client_id=1043&scope=team%3Aread&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%2Fauthorized&state=CfDJ8G93PB5gK1dHuT4wAt21M8nBPAhHwCVRIBhS3woVO7BEikK6exaseJAAwTlGXiim0TQvpOZKhVd1gUK0InCLOusNdQdfnXHV7saoO9TOJW9J1VhbKDaY0hFGGbpUiROE6e6gbiY6h_aPHCGwTiRGzp0KzMSG4aH3aeicbEtsmfwJlQywwdKtsFvIFx3yVUd_MHriqlfrluy6hzu2HZHypizZMCIRRhoEBZ2qWl_hB5Dllh810YZNjBZSjOk_F4h9TLqwwq0Joqcg0xiaplwTjeM` would be allowed.

Since you are using regexes, I think the literal character `-` must be escaped in most regex engines. If you'd document your allowed characters for your state somewhere that would be great, too 😇

**Comment by kyprizel** [comment]
Well, may be. try again.

**Comment by Trolldemorted** [comment]
It is different now:

![grafik](https://user-images.githubusercontent.com/10261186/99909559-9a243b80-2ce9-11eb-9dd1-405e4e0504ca.png)
