### ISSUE TITLE
Get the team logo URL

### ISSUE THREAD

**Issue by Trolldemorted** [ctftime/ctftime.org#179]
If we get #178 done we'd love to display the ctftime team logos in our scoreboard.

Unfortunately the link to them cannot be easily derived from the team id:
`/media/cache/cc/65/cc6521cedbb399a9239eca7ec0c349c6.png`

nor is it exposed in the team api:
```
{
  "rating": [],
  "name": "ENOFLAG",
  "country": "DE",
  "academic": true,
  "id": 1438,
  "aliases": ["LEGOFAN", "lastemail", "ENOwOFLAG"]
}
```

Can we get a team's logo without crawling your html somehow?

**Comment by Trolldemorted** [comment]
Since #178 is long done and BambiCTF will happen on Saturday, could you give us a heads-up whether you will add this to the API in the near future @kyprizel?

If you opensource ctftime we are naturally willing to submit a pull request, if that would help the matter.

**Comment by kyprizel** [comment]
Added "logo" field, but it returns original image submitter by the team, not resized one.
