### ISSUE TITLE
always print timezones with times

### ISSUE THREAD

**Issue by tecknicaltom** [ctftime/ctftime.org#18]
When you're logged in, times are given in your default time zone. When you're not logged in though, times are given in UTC, but they do not say that in most places. This can be even more confusing if you don't realize that you're not logged in.

I think that times should always include the time zone, even if you are not logged in.

**Comment by kyprizel** [comment]
Done.

**Comment by tecknicaltom** [comment]
This seems to have made the printing of times in ranges inconsistent. For instance, when not logged in, PlaidCTF 2015 at https://ctftime.org/event/185 says:
April 17, 2015, 9 p.m. — 19 April 2015, 21:00 UTC
note that the start time is in a 12 hour clock but the end time is in a 24 hour clock.
