### ISSUE TITLE
Get the team university affiliation

### ISSUE THREAD

**Issue by Trolldemorted** [ctftime/ctftime.org#180]
Similarily to #179, we usually display the university of a team, if it has one:
![grafik](https://user-images.githubusercontent.com/10261186/99901425-ddb18200-2cb6-11eb-957e-dc1d0497eb8e.png)

Unfortunately, your team API only gives us `true` or `false`:
```
{
  "rating": [],
  "name": "ENOFLAG",
  "country": "DE",
  "academic": true,
  "id": 1438,
  "aliases": ["LEGOFAN", "lastemail", "ENOwOFLAG"]
}
```

Can we get a team's university without crawling your html somehow?

**Comment by kyprizel** [comment]
Please, try now?

**Comment by Trolldemorted** [comment]
Looks good, thanks!
