### ISSUE TITLE
A team was automatically created on my name because I didn't have CTFTime.com account, now I cannot join the team it's pending for months 

### ISSUE THREAD

**Issue by izcatoriz** [ctftime/ctftime.org#182]
Hi! Could you please assist with joining my team too?

It said if I am the first member I will be joined automatically, it hasn't happened yet.

team name: S0pht
user name: izcatoriz

and this is me!

Thanks!

**Comment by c12yptonic** [comment]
Hi how did you solve this issue @izcatoriz . I am stuck at a similar juncture.
