### ISSUE TITLE
Rating points for CTF 313 2020 is broken (everyone got 40+ rating points) 

### ISSUE THREAD

**Issue by QzSG** [ctftime/ctftime.org#185]
https://ctftime.org/event/1207

Every team that participated in it seems to be rank 1 and awarded 40+ rating points which has pretty much broken the rating boards?

Noticed because someone I knew who is always on the last few in many CTFs suddenly got to the top of the country rating leader board and found out everyone in this ctf basically had free absurd ratings.

Can the CtfTime team please check it out?

**Comment by kyprizel** [comment]
Fixed
