### ISSUE TITLE
Some time error in our CTF event.

### ISSUE THREAD

**Issue by ghost** [ctftime/ctftime.org#189]
Hello Team,
There has been some glitch in timing of CTF event. The exact time is:- Sun 17th January 2021, 10:00  IST to Sun 17th January 2021, 16:00 IST . But the event is showing Sun, 17 Jan. 2021, 15:30 IST — Sun, 17 Jan. 2021, 21:30 IST. And I am not able to edit it to. Is there any other way to change it or the admins will change it.
If admins, then we request to change it.

Thanks!

**Comment by kyprizel** [comment]
Please, provide event id and exact datetimes in UTC.

**Comment by ghost** [comment]
Our event id is 1232.

17th January 2021 04:30 am UTC - 17th January 2021 10:30 am UTC.

**Comment by ghost** [comment]
Hello,
I think it's not been updated yet!
