### ISSUE TITLE
can't add team alias?

### ISSUE THREAD

**Issue by psifertex** [ctftime/ctftime.org#19]
MIBH has been playing under slight variations of our team name for kicks (and also because we can't decide on a good acronym) but I can't add the latest name. While I originally entered it into ctftime as "Magic Inuits Bringing Horses", we had a problem with our plaid registration and ended up playing as "MagicInuitsBringingHorses".  When I try to add that alternate spelling, it says: "Team with such name already exists". Is that because the plaid results are already back and that team was automatically created? Sorry for not getting this in sooner if so.

**Comment by kyprizel** [comment]
"Magic Inuits Bring Horses" is an alias to MIBH. Merged "MagicInuitsBringingHorses" to MIBH.

**Comment by psifertex** [comment]
Thanks! Sorry for the extra effort.
