### ISSUE TITLE
Unable to add results.

### ISSUE THREAD

**Issue by sc4rygh0st** [ctftime/ctftime.org#190]
Hey team,
We are not able to add results in our event.

Our event id is 1232.

We have attached the results file here. Can you please update?
[results.txt](https://github.com/ctftime/ctftime.org/files/5826455/results.txt)

**Comment by kyprizel** [comment]
Why can't you add it?

**Comment by nihalumar** [comment]
It's showing error.
`Result saving error`
`Format error, See FAQ`

Is there any other way we can do it?

**Comment by sc4rygh0st** [comment]
It's showing error.
`Result saving error`
`Format error, see FAQ`

I have tried a lot but it's not working. Showing the same errors.
Is there any other way to do it?
