### ISSUE TITLE
Need to change the scoreboard

### ISSUE THREAD

**Issue by IAM1here** [ctftime/ctftime.org#192]
Hello, we had a ctf named shadowCTF on 26th jan 2021, and my team made a mistake, They added wrong details on scoreboard, So my concern is i wanted to change the scoreboard, Is it possible, Please help!
Thanks!

**Comment by kyprizel** [comment]
You can submit new scoreboard now.

**Comment by IAM1here** [comment]
> You can submit new scoreboard now.

Where shall i submit it ? here? The ctf's link is here: https://ctftime.org/event/1245/

**Comment by IAM1here** [comment]
Hello @kyprizel , i also made the same request to change the scoreboard via the feedback option in the website itself!

**Comment by kyprizel** [comment]
just submit the new scoreboard via ctf management interface.

**Comment by IAM1here** [comment]
Hello, Can i rechange the scoreboard there? Because i am unable to find an option to rechange it! I am a bit new to Ctftime! When i go to the manage results options ,It says that the scoreboard was approved and i cannot rechange it , There is no option i can see!

**Comment by kyprizel** [comment]
Just dig harder. Submit the screenshot please.

**Comment by IAM1here** [comment]
here is the screenshot : this was what my team did by mistake, and i wanted to change this to the actual values!
![Screenshot (12)](https://user-images.githubusercontent.com/35186937/106172850-49353580-61b9-11eb-85c7-b2ea0587ca92.png)

**Comment by kyprizel** [comment]
and now?

**Comment by IAM1here** [comment]
Yes we are good to go now, Thanks for the help!

**Comment by IAM1here** [comment]
Resolved!

**Comment by nauliajati** [comment]
Hi, i have same problem too, i can't rechange the scoreboard, here is my event: https://ctftime.org/event/1601/

**Comment by nauliajati** [comment]
and this is the actual my CTF scoreboard event:
{
	"standings": [
		{ "pos": "1", "team": "Bratasena Jr", "score": "5685" },
		{ "pos": "2", "team": "TryHardest", "score": "5509" },
		{ "pos": "3", "team": "PANITIA", "score": "5445" },
		{ "pos": "4", "team": "S3 Napan", "score": "5001" },
		{ "pos": "5", "team": "Cape pakai K", "score": "4606" },
		{ "pos": "6", "team": "Enigma", "score": "3503" },
		{ "pos": "7", "team": "Sobatadit", "score": "3116" },
		{ "pos": "8", "team": "Lontong Balap", "score": "3036" },
		{ "pos": "9", "team": "\u+002Enoidea", "score": "2867" },
		{ "pos": "10", "team": "E = mc\u+00b2", "score": "2780" },
		{ "pos": "11", "team": "cyber team>", "score": "2780" },
		{ "pos": "12", "team": "Mantep\u+003A\u+0029", "score": "2616" },
		{ "pos": "13", "team": "elpsyponkotsu", "score": "2344" },
		{ "pos": "14", "team": "PELAJARTAMPAN", "score": "2213" },
		{ "pos": "15", "team": "FINAL FANTASY 8", "score": "2193" },
		{ "pos": "16", "team": "Pickleboi", "score": "1636" },
		{ "pos": "17", "team": "Rasberry", "score": "1380" },
		{ "pos": "18", "team": "Stemsago", "score": "1200" },
		{ "pos": "19", "team": "MB3 Cyber Team", "score": "1144" },
		{ "pos": "20", "team": "ThermalDryer", "score": "900" },
		{ "pos": "21", "team": "SMEGA", "score": "900" },
		{ "pos": "22", "team": "\u+002Fetc", "score": "744" },
		{ "pos": "23", "team": "YTTA", "score": "600" },
		{ "pos": "24", "team": "RN Team", "score": "600" },
		{ "pos": "25", "team": "Ummu Du'a", "score": "600" },
		{ "pos": "26", "team": "Saitama Crew Xploit", "score": "600" },
		{ "pos": "27", "team": "NagaSec", "score": "300" },
		{ "pos": "28", "team": "unknown", "score": "300" }
	]
}

**Comment by kyprizel** [comment]
Please, reupload.

**Comment by nauliajati** [comment]
Awesome, solved, Thanks!

**Comment by AliMirlou** [comment]
Hello, we have made a similar mistake. Can you kindly enable us to update our scoreboard as well please?

https://ctftime.org/event/1673/

**Comment by AliMirlou** [comment]
@kyprizel Hello, we have made a similar mistake. Can you kindly enable us to update our scoreboard as well please?

https://ctftime.org/event/1673/

**Comment by kyprizel** [comment]
done

**Comment by AliMirlou** [comment]
@kyprizel Thanks. Fixed.

**Comment by simran-kathpalia** [comment]
Hi, we too made a mistake while uploading the scoreboard and want to reupload the scoreboard. Could you please help? Will we still be able to keep the rating points? @kyprizel 
https://ctftime.org/event/1812

**Comment by kyprizel** [comment]
try now

**Comment by simran-kathpalia** [comment]
Still unable to change.

**Comment by Skryptonyte** [comment]
Hi, I would also like to reupload the scoreboard with small amendments. One team had their scores wrongly assigned to another team of a similar name. Moreover, we also found there were fake accounts of top teams created as well.

https://ctftime.org/event/1758

Will the rating points be affected here though?

**Comment by Skryptonyte** [comment]
We also want to amend our scoreboard as well because we just came to know one team had their points wrongly assigned to another ctf team of a similar name. But will the scoreboard reupload affect the event rating?  @kyprizel

**Comment by kyprizel** [comment]
Try to reupload.

**Comment by Skryptonyte** [comment]
Still unable to reupload.

**Comment by simran-kathpalia** [comment]
> Hi, we too made a mistake while uploading the scoreboard and want to reupload the scoreboard. Could you please help? Will we still be able to keep the rating points? @kyprizel https://ctftime.org/event/1812

Could you please check this again?

**Comment by HrisheekeshDandekar** [comment]
https://ctftime.org/event/1904/result 
@kyprizel The platform has edited some team names wrongly. Is there a way to upload again? I cannot find the option.

**Comment by HrisheekeshDandekar** [comment]
https://ctftime.org/event/1904
@kyprizel 
The platform has edited some team names wrongly. Is there a way to upload again? I cannot find the option.

**Comment by yoshino-s** [comment]
Hey @kyprizel  , another request to resubmit scoreboard https://ctftime.org/event/2061

**Comment by asareynolds** [comment]
@kyprizel Hello, we would like to resubmit our scoreboard please! https://ctftime.org/event/2637

**Comment by sxsxno** [comment]
@kyprizel Hello, we'd like to resubmit our scoreboard please https://ctftime.org/event/3071/

**Comment by h0i5** [comment]
@kyprizel Hello, we would also like to resubmit our scoreboard to add support for certain chinese team names: [3171](https://ctftime.org/event/3171/)

**Comment by sl-op** [comment]
Hey @kyprizel 
We have added link to the scoreboard Json file but it hasnt updated yet, and we only have remaining 3 days for end of voting.
Kindly help us as soon as possible
https://ctftime.org/event/3136/

**Team SecLeaf**
