### ISSUE TITLE
Every action met with "OK (not really, contact info@)"

### ISSUE THREAD

**Issue by micpap25** [ctftime/ctftime.org#194]
Every action I take on CTFTime is met with "OK (not really, contact info@)", on both my personal and school emails. I cannot create or join teams, save profile info, or **delete my account**. I could not send this as feedback to the site because I got the same response. My account is completely non-functional and I have no idea why. Please fix this issue, or at least let me contact directly so I can ask for my account to be removed.

**Comment by kyprizel** [comment]
Your account was deleted.

**Comment by TomiyokaGiyu** [comment]
I am also having same problem

**Comment by 5k4r5** [comment]
Me too.

**Comment by jtsec92** [comment]
Hi, I'm getting this too on my account.
