### ISSUE TITLE
Adding Past Event

### ISSUE THREAD

**Issue by sc4rygh0st** [ctftime/ctftime.org#199]
Hey,
Is there anyway to add our past events? Like: We have organized a CTF in 2020 but at that time, we were not having any idea of ctftime events. Is there anyway to add the past event?

**Comment by sc4rygh0st** [comment]
I added a event of 2020 to my team. We don't want ratings for that event. We just want to add that to our team. Can admins accept that & add it?

Event id= 1352

**Comment by kyprizel** [comment]
done
