### ISSUE TITLE
Team API returns 500 Internal Server Error for teams without team logo

### ISSUE THREAD

**Issue by ldruschk** [ctftime/ctftime.org#200]
Hi,

as the title says, the API endpoint https://ctftime.org/api/v1/teams/151362/ returns an internal server error when querying teams without a team logo. (To test I created another team with a logo: https://ctftime.org/api/v1/teams/151899/)

This is reproducible by adding/removing a logo to the first team.

**Comment by kyprizel** [comment]
Thanks, fixed.
