### ISSUE TITLE
Joining team as first member

### ISSUE THREAD

**Issue by zeyu2001** [ctftime/ctftime.org#203]
Hi! I've participated in a few CTFs with the following team name, but only recently realised that the team name is already listed on CTFtime. Could you please assist in approving my request to join my team?

Team name: Social Engineering Xperts
Username: zeyu2001

If you need proof, I'm using the same handle, zeyu2001, [here](https://umdctf.io/teams/342).

**Comment by Fawl** [comment]
I'm also in the team!
