### ISSUE TITLE
Bambi CTF #5 should have been unrated :(

### ISSUE THREAD

**Issue by Trolldemorted** [ctftime/ctftime.org#205]
I am sorry to be a burden, but we just noticed that our Bambi CTF 5 has yielded points to the participating teams. We asked our guy who created the event and he isn't 100% sure whether there was a "unrated" checkbox, but if where was one he'd definitely click it.

Can we still make that event unrated, or is it too late now?

https://ctftime.org/event/1253

**Comment by kyprizel** [comment]
Why should we?

**Comment by Trolldemorted** [comment]
Well it is a beginner CTF with intentionally easy vulnerabilities, and most well-known teams knew this and supervised their rookies instead of playing themselves.

If you want the points to truly denote a team's skill, you shouldn't count Bambi CTF. Next time we will be extra careful to have it unrated, of course.

**Comment by kyprizel** [comment]
I don't see a problem if it has a rating.
