### ISSUE TITLE
Event this weekend. Approve Needed.

### ISSUE THREAD

**Issue by aminekaabachi** [ctftime/ctftime.org#206]
I am part of a community and we are organizing a CTF. Due to Covid circumstances, we submitted late the CTF to http://ctftime.org.  We usually get a response within a day or two. Can you please accept the event before the weekend?

Event id: 1355.

Thank you in advance.

**Comment by yurilaaziz** [comment]
+1

**Comment by ncfoa** [comment]
+1

**Comment by NabilHouidi** [comment]
:+1:

**Comment by mohamed-chemlali** [comment]
+1

**Comment by houssemeddinesassi** [comment]
+1

**Comment by kortwael** [comment]
+1

**Comment by aminekaabachi** [comment]
@kyprizel  any chance this can be approved today?
Thanks in advance.
