### ISSUE TITLE
We select the wrong end date for enowars5 :(

### ISSUE THREAD

**Issue by Trolldemorted** [ctftime/ctftime.org#208]
Sorry to bother you again, but apparently we have selected the wrong end date for [enowars5](https://ctftime.org/event/1340/).

Eventid: `1340`
Current end date: `So, 11 Juli 2021, 22:00 UTC`
Correct end date: `Sa, 10 Juli 2021, 22:00 UTC`

**Comment by kyprizel** [comment]
fixed
