### ISSUE TITLE
CTF rating reset when one of the organizers left

### ISSUE THREAD

**Issue by vient** [ctftime/ctftime.org#211]
Hi. As I understand, CTF loses rating when organizers change. Seems logical when previous year it was team A and now team B since they may be completely unrelated and this is unsolvable.

Now consider current year 0CTF [Quals](https://ctftime.org/event/1356)/[Finals](https://ctftime.org/event/1357). In previous years 0CTF had two organizer teams, 0ops and eee. This year it is only 0ops, so one organizer team is same as before but ctf still lost all its rating ([nearly 100](https://ctftime.org/ctf/99)). While it is in the spirit of strict "org change - rating lost" rule, this situation does not seem fair to me. In this particular case a compromise may settle better: cut rating in half. On the other hand, how to resolve these situations generally? What do you think?

**Comment by kyprizel** [comment]
That's not b/c organizers changes but b/c of event type change. Fixed.

**Comment by vient** [comment]
What does "event type change" mean? I don't see any differences between 2020 and 2021 quals besides organizers change.

**Comment by kyprizel** [comment]
That's internal event type (quals/finals/single).
