### ISSUE TITLE
"I'm in the team!" should be removed from the page in case of team without admin since requests are not processed by portal admins

### ISSUE THREAD

**Issue by level44** [ctftime/ctftime.org#212]
Scenario:
- team name already in the database without team members
- information on the page says "There is no registered members of this team. Click on "I'm in the team" - be the first."
- somebody is trying to join the team by clicking on "I'm in the team!"

Observed:
- new pending request created but not processed by ctftime.org Admins

Expected:
- request shall be processed or future removed at all to have clear situation (no possible to join the team if not created in the portal manually before first CTF)

**Comment by kyprizel** [comment]
Most requests are automatic but there are some restrictions to prevent spam.

**Comment by Mirashx86** [comment]
Some restrictions?
What is eases way to join to our team?

**Comment by Mirashx86** [comment]
> Most requests are automatic but there are some restrictions to prevent spam.

Some restrictions?
What is eases way to join to our team if it exist in DB?

**Comment by kyprizel** [comment]
Join one specific team, not trying to join a lot.

**Comment by level44** [comment]
I've sent a one request to join one team in April....

**Comment by level44** [comment]
My proposition is to change from pending to rejected in case that request is marked as spam?

**Comment by dmichal** [comment]
I have the same problem: I sent a request to join one team two months ago and it's still "Pending". If it was classified as spam, the classifier shall be improved, because now it obviously doesn't work as expected.

**Comment by level44** [comment]
@kyprizel I've just found issue #97 and it seems that the problem is well known since years - there is a comment "Create teams before the event." - so it seems that my request to remove possibility to join already created teams without team members is right

**Comment by dmichal** [comment]
The problem seem to be very common and there are a lot of people facing it: #197 #198 #210. It's definitely not about sending join request to many teams by one user as @kyprizel said above.

**Comment by level44** [comment]
@dmichal you are right I've just found a few interesting posts on [twitter](https://twitter.com/CTFtime/status/1382348098505207822) and [reddit](https://www.reddit.com/r/securityCTF/comments/co2a6i/team_status_pending_ctftime/). Anyhow my intention while submitting this ticket was to improve ctftime.org webpage - if it's not possible - that's fine I can live with that :)

**Comment by Mirashx86** [comment]
I'm confused. From what you gentlemen write I will not be able to join my team. Instead, I have to create another database entry that does not summarize my accomplishments so far. Consequently, I will not be able to show off my results to potential employers. As for me this option should be removed if it does not work or should be fixed.

**Comment by kyprizel** [comment]
Actually a lot of people can join their teams after the event. There are just some restrictions to prevent mass takeover.
For example - if you're trying to join only team in most cases it'll be successfull.

I'm working on improvement of takeover prevention mechanims but to be honest there is not enough data to make false-positive free decisions.

**Comment by Mirashx86** [comment]
Now I get the point. I don't know about others, but in my case the situation is that my team participated in several CTFs and only after a year we decided that we need to formalize our activity.

I don't know if you have information on who was a member of the team at the event, but it seems to me that would be very helpful.

**Comment by ethan0924** [comment]
So how do you join this unmanned team?
Will the application administrator pass?
