### ISSUE TITLE
Ability to make an unclaimable team

### ISSUE THREAD

**Issue by kerupuksambel** [ctftime/ctftime.org#216]
I think I accidentally found a bug that could create a team that can't be deleted and claimed.

## How to replicate :
1. Make a team
2. Mark the team as "Invite only"
3. Join the team with the invite code
4. Remove yourself from the team
5. Now the team can't be deleted or claimed, since it's invite only

## Impact :
It could make a team that can't be deleted/claimed, and could make a team can't register their favorable name.

## Mitigation :
Make the team public after last member quit

**Comment by kyprizel** [comment]
Thank you, fixed!
