### ISSUE TITLE
Issue in point calculation.

### ISSUE THREAD

**Issue by overnine** [ctftime/ctftime.org#22]
0ops magically got an extra 100 points on the scoreboard, a simple summation of thier ratings this year will show the same:

https://ctftime.org/team/4419

**Comment by kyprizel** [comment]
Events organizers get 2xevent weight for organized CTF events.

**Comment by overnine** [comment]
That is not documented nor seems like a valid way to rate team versus each others. I don't see the logic in this. The  system should really be changed to an elo system or something to represent a more realistic ranking.

**Comment by psifertex** [comment]
See #6. That's a separate discussion. Points to CTF organizers makes sense in context of the current scoring algorithm. Otherwise teams are disincentivized from running events. I agree that ELO or TrueSkill something else might work better, but given the current algorithm now, it's appropriate.

**Comment by psifertex** [comment]
Also, see: https://ctftime.org/faq/#rating-formula

```How was rating counted?
Read more: Rating formula

Also, CTF organizers get rating points for their events.
```

I guess it could be more verbose, but it's there.

**Comment by overnine** [comment]
You´re right. I guess we will stick to issue #6.
