### ISSUE TITLE
Approved CTF no longer approved

### ISSUE THREAD

**Issue by 0xmmalik** [ctftime/ctftime.org#221]
My CTF (https://ctftime.org/ctf/637/) was previously approved, but it now shows up as Approved: False. Why is this the case and is there something I need to do to fix it?

**Comment by 0xmmalik** [comment]
@kyprizel -- Is there anything I need to do about this or will it be re-reviewed later?

**Comment by kyprizel** [comment]
You created some spam events so approve was cancelled.

**Comment by 0xmmalik** [comment]
@kyprizel -- Our event is a legitimate CTF and if there's no way to ensure that information is entered correctly or if there is no way to correct misentered information, that's an issue with the website, not with whoever posted the event. I suggest making it possible to revise and delete events after the fact. In the meantime, I ask that you or someone on the team approve our CTF again, as there was no real reason for removing its approval in the first place. (Note that the "spam events" in question was a single event created that was inadvertantly labeled with the wrong organizing team and _slightly_ incorrect dates; there is no way to modify this after the event is created.)

**Comment by kyprizel** [comment]
I can approve CTF again after your commitment to double check the event info before posting.

**Comment by 0xmmalik** [comment]
@kyprizel — That’s unfortunate considering I can’t post an event again until you approve the CTF.
