### ISSUE TITLE
Event result updating

### ISSUE THREAD

**Issue by won0-kim** [ctftime/ctftime.org#223]
Hello

I'm one of the managers of Hacker's Playground.
I uploaded only the top 20 teams on the scoreboard by mistake and cannot modify it anymore. I tried to resolve JSON errors, but it was my bad. I've already sent this by the feedback but because it is a bit urgent, please understand that I'm contacting you through multiple channels.

Thank you

**Comment by kyprizel** [comment]
try now

**Comment by won0-kim** [comment]
@kyprizel I cannot find the modify button.  there are still only 20 teams on the scoreboard.

**Comment by kyprizel** [comment]
and now?

**Comment by won0-kim** [comment]
Thank you!
