### ISSUE TITLE
My CTF is not listed in "upcoming CTFs"

### ISSUE THREAD

**Issue by hakatashi** [ctftime/ctftime.org#226]
Hello, I am an organizer of [TSG CTF](https://ctftime.org/ctf/294).

I created "TSG CTF 2021" event from "Manage CTFs" page about 2 weeks ago. The creation seemed to be successful, but the event is not shown up in "upcoming CTFs" page.

I can still access edit page of the event and the URL suggests me that the id is 1431, but https://ctftime.org/event/1431 is also 404. Please could you fix that?

**Comment by kyprizel** [comment]
too little data to accept

**Comment by hakatashi** [comment]
@kyprizel Okay, I updated description.

**Comment by hakatashi** [comment]
Thank you!
