### ISSUE TITLE
Better Support for Team Merging

### ISSUE THREAD

**Issue by nnamon** [ctftime/ctftime.org#23]
Currently, team merges are done by submitting feedback through the contact us form and the merge has to be done manually by an admin.

It would be great if the admin of multiple teams could merge them through an interface so it reduces load on the admin and would really streamline the processes and handling the restrictions of CTF registrations.

**Comment by kyprizel** [comment]
Now there is no good way to "revert" the team merge. As soon as we understand how to fix it - we'll allow it.

**Comment by nnamon** [comment]
Thanks for the reply. If you do need any grunt work doing the verifications, I would be happy to offer my assistance. 

One idea I have is to perhaps include a feature in settings that creates a derivative of the team's name based on a supplied regex so that alias will be in effect before the scoreboard is submitted to ctftime. Of course, the derivative has to be majorly similar to the original. Perhaps a predefined list of common regexes ctfs use would prevent teams from hijacking other team names by coercing the alias through restrictive regexes. This would allow teams to pre-emptively create their aliases before registration and ease merge requests to purely across different teams. 

As a side note: could I please get my main team Dystopian Narwhals and the sharif ctf compliant team dystop_narwhals merged please? I've submitted a merge request.

**Comment by kyprizel** [comment]
Why haven't you added alias "dystop_narwhals" to your team **before** the CTF?

**Comment by nnamon** [comment]
Oh! I didn't realise that is an option. That does make it a lot simpler then. Thanks.
