### ISSUE TITLE
Merge (alias ?) error

### ISSUE THREAD

**Issue by yukiech** [ctftime/ctftime.org#230]
Hi,
I've tried for weeks to merge and/or link second team as alias but the website form won't let me.

Always the same error : "Team merging error.  - Teams having uncommon members in alias can not be merged."
Even with both team having exactly the same members.

Context: We started doing CTFs a month ago and for an unknown reason it looks like we did some under "42 Lausanne" (164042) instead of "42Lausanne" (161029). We'd like to be able to "merge/alias" those to get a "centralised" CTFs history. (as "42Lausanne" (161029))

Is there anyhting we can do ?
Thanks :)

**Comment by m0rphtail** [comment]
having the same issue, no idea why, I have 2 teams with only me as a member, but unable to merge them.

**Comment by kyprizel** [comment]
There was a nasty bug with GDPR users. Please, try now?

**Comment by yukiech** [comment]
Still the same. "Teams having uncommon members in alias can not be merged."

**Comment by kyprizel** [comment]
Try now please

**Comment by yukiech** [comment]
"Teams merge request was sent." :thumbsup:

**Comment by SionAghajani12** [comment]
There is  no submit button the merge has been sent but the merge is no actually done can you please let me know how it works?
> Try now please
