### ISSUE TITLE
My Team points are displayed on another team

### ISSUE THREAD

**Issue by InTruder-Sec** [ctftime/ctftime.org#231]
Our CTF points are getting displayed on team cyber. I am leading CYBER<X> for many CTF's hosted on CTFtime. But points scored by us on my of the CTF's are getting displayed on cyber profile. Please help us out.

**Comment by kyprizel** [comment]
Please, provide links for teams and events?

**Comment by InTruder-Sec** [comment]
Hey ,@kyprizel

 MY team:- https://ctftime.org/team/166365
Team with our points:- https://ctftime.org/team/15665

CTF events:- https://ctftime.org/event/1440
                     https://ctftime.org/event/1312

**Comment by InTruder-Sec** [comment]
Hey, @kyprizel 

Any updates?

**Comment by kyprizel** [comment]
I'm working on it

**Comment by kyprizel** [comment]
Thanks. Fixed:
https://twitter.com/CTFtime/status/1448232835647684615
