### ISSUE TITLE
Cannot join our team

### ISSUE THREAD

**Issue by w3ich3rt** [ctftime/ctftime.org#233]
Hey guys, 

nobody of us can join our team. Even smiley our team leader is not able to join it and approve us.
Can anyone please help us?

Out teamname is: 
> it-sec.fail

And the id is:
> 156112

Thanks for your help!

Kind regards!

**Comment by w3ich3rt** [comment]
We still need some help :)

**Comment by w3ich3rt** [comment]
Could you please help us? We just want to join our team to participate on events, post writeups and so on!

**Comment by GreenOlmSecurity** [comment]
Ping

I also wrote a message via the feedback formular on the website. Waiting to join the team since 31. August 2021 22:39:34 (Nickname on ctftime is Smily)

**Comment by w3ich3rt** [comment]
Thanks for your help guys from ctftime.org. A teammember was finally able to join the team and could accept the pending requests. So your help is not necessary anymore.

Quite nice support :-)
