### ISSUE TITLE
Reply Cyber Security Challenge 2021 scoreboard seems incorrect

### ISSUE THREAD

**Issue by egonny** [ctftime/ctftime.org#235]
The [Reply Cyber Security Challenge 2021](https://ctftime.org/event/1436) scoreboard seems incorrect:

* The first place team is missing from the scoreboard.
* Scores seem incorrectly calculated; the 421st (out of 423) team received 27.896 points, the 422nd received 13.948 points.

**Comment by kyprizel** [comment]
Fixed, thanks. There were some bugs in scoreboard data.
