### ISSUE TITLE
I can't restore the team alias

### ISSUE THREAD

**Issue by ghost** [ctftime/ctftime.org#239]
Hello. on 28.10 I accidentally deleted one of my team aliases. unfortunately now I cannot restore it because a new team has been created with the name of the deleted alias. Is it possible to assign the alias to my team?  Unfortunately I cannot use the merge teams option, because it has been 2 weeks since I took part in the event. I would really appreciate your help, because I have lost scores from 2 competitions (over 20 points). The strange thing is that the score from one competition has not been deleted and the team name in the competition scoreboard has automatically changed to the other alias. Moreover the deleted alias was needed, because by default my team name has a space in it and I had cases when I did not receive points (the name in the scoreboard was without spaces)

**Comment by kyprizel** [comment]
Why have you deleted it?
Please provide team id and alias anyway.

**Comment by ghost** [comment]
https://ctftime.org/team/141007. I thought that results from competitions are assigned to a team, not to an alias. I wanted to change name in Team information and I thought that I cannot have identical name as alias(now i know that i can't change the name).  Team created from alias: https://ctftime.org/team/168647. It was merged with LiquidTeam because I wanted to see how the merge works ( i merged teams yesterday). I guess we won't get the points from the DEF CON CTF Qualifier 2021 because it has been a long time since we did it. But we really would like to regain points from Deadface (competition ended on 17.11.2021), because it was about 20 points and we dropped several dozen positions in the overall ranking).
Sorry for the problem and thank you very much for your help.


EDIT: Now I noticed that even though both competitions ended more than 2 weeks ago, after merging the teams the scores were added up from both accounts. (it concerns a merge made yesterday between 2 other aliases "Liquid_Team" and "LiquidTeam")
If I merge Liquid Team and Liquid_Team, will it add up the scores from both accounts as in the previous case? I will not lose scores from the main account?

**Comment by kyprizel** [comment]
ok, teama are merged. but be careful next time.

**Comment by kyprizel** [comment]
And please, do not create merge requests without a reason.
