### ISSUE TITLE
New member authorization didnt work 

### ISSUE THREAD

**Issue by psifertex** [ctftime/ctftime.org#24]
had a request from a teammate that when I tried to approve, I got the error: "Membership requests processing error"

I gave him the team hash so he could join that way, but it'd be good to double check the other process too.

**Comment by kyprizel** [comment]
Thanks, I'll check it asap.

**Comment by kyprizel** [comment]
Can you check now?

**Comment by psifertex** [comment]
So the email links are invalid (start with ///), and once I got to the page the two requests I had were already approved. I'm checking to make sure nobody else accidentally approved them. can any team member approve, or only the captain?

**Comment by kyprizel** [comment]
Any member can.
Links fixed - made them https-only.

**Comment by kyprizel** [comment]
Is it fixed now?
