### ISSUE TITLE
https://ctftime.org/event/foobar gives HTTP 500 in my session

### ISSUE THREAD

**Issue by Trolldemorted** [ctftime/ctftime.org#240]
While it works for others and also in an incognito brower window, in my session I am getting http 500s only:

```
500

Something is going wrong — are you trying to hack me? Back to the main page.

Ok, ok — here is your flag: 38b15f9dc11199fceff783291929a6c2
```

![grafik](https://user-images.githubusercontent.com/10261186/139749292-723f2b64-3c36-4b95-90f5-303b0581a946.png)

**Comment by kyprizel** [comment]
Sorry. Fixed.
