### ISSUE TITLE
unable to recover team

### ISSUE THREAD

**Issue by frankli0324** [ctftime/ctftime.org#241]
We have a team which name is "L", however single-lettered team names are not allowed(from what I was told), so we created our team under the name of "L-team". However, XCTF organizers imported our scores as "L_XCTF", which is aliased to "L", and the team was administrated by "luo". However, it's unfortunate that luo lost his google account for registering ctftime, therefore unable to accept our own join requests. What's more annoying is that someone else we don't recognize participated in some events under the name of "L", which caused that the two team has some conflicting records.

Is there a chance we can get our records merged somehow? This issue has confused us for years. And we tried submitting forms on ctftime, but no responses.

**Comment by kyprizel** [comment]
Well, looks like it'd be better to choose more unique name.

**Comment by frankli0324** [comment]
Our team was founded over 6 years ago, and we only accept undergraduates from our university. It's not possible for us. Also that's NOT the only, nor the main issue. Don't we have a slightest chance merging the two teams?(7929&11724) I can prove the authenticity of my words with im conversations if needed, privately...

**Comment by kyprizel** [comment]
Can luo send me his email and tell if he's ok with this merge?

**Comment by frankli0324** [comment]
I'll PM him.

**Comment by timofg** [comment]
> Can luo send me his email and tell if he's ok with this merge?

I'm luo, the email I used to sign up for might have been whatfukaday@gmail.com，I forgot the password because I had not used it for many years。

**Comment by kyprizel** [comment]
I approved your membership for team 11724

**Comment by frankli0324** [comment]
thanks, I guess that it's impossible to merge the teams then?

**Comment by kyprizel** [comment]
You can try to merge them yourself.

**Comment by frankli0324** [comment]
tried, but failed with "You can't merge teams participated in events later than 2 weeks after the event ends".

**Comment by kyprizel** [comment]
Try now

**Comment by frankli0324** [comment]
Many thanks!!!
