### ISSUE TITLE
m0leCon CTF Finals not having the correct weight

### ISSUE THREAD

**Issue by mr-96** [ctftime/ctftime.org#243]
Hello,

Our CTF (https://ctftime.org/event/1456) has rating 0 while there has been a previous edition with positive rating (https://ctftime.org/event/1135).

We know that it's an onsite event, but it had a qualifier (https://ctftime.org/event/1325) and we allow qualified teams to play online if they can't come to Italy, so we believe that with these rules the event should have a weight.

Thank you!

**Comment by kyprizel** [comment]
fixed.

**Comment by mr-96** [comment]
Hello, now the weight is correct but public voting is still up to 25. Can you fix also this please? Thank you!
