### ISSUE TITLE
Require to modify event result.

### ISSUE THREAD

**Issue by ManassehZhou** [ctftime/ctftime.org#246]
Hi there,

I am one of the organizers of N1CTF. I uploaded a scoreboard with the wrong ranking by mistake. When I tried to modify the uploaded result from ctftime.org, I found there is no such API. So I'm wondering if you can help me to revoke the mistaken scoreboard?

Thank you!

**Comment by kyprizel** [comment]
try to reupload now

**Comment by ManassehZhou** [comment]
Thanks
