### ISSUE TITLE
Event not showing up in "upcoming CTFs" (BSides Algiers 2021 Finals)

### ISSUE THREAD

**Issue by chenx3n** [ctftime/ctftime.org#249]
Hi, I am one of the organizers of [BSides Algiers](https://ctftime.org/ctf/527/).

I created "BSides Algiers Finals 2021" event from "Manage CTFs" page but the event is not showing up in "upcoming CTFs" page.    
My guess is that it's because the event hasn't been approved yet, that is why I'm inviting you to look at the official BSides calendar [here](http://www.securitybsides.com), you'll find that BSides Algiers Finals is indeed scheduled for the 8th and the 9th of January 2022.  
Sorry for rushing this out, but we're in a kind of a hurry since we need to provide the CTFtime link of the event to a potential sponsor.  
Thank you for understanding and good luck with everything.

**Comment by kyprizel** [comment]
Please, check if everyting is ok now.

**Comment by chenx3n** [comment]
Yes, everything is okay.
Thank you for the quick reply.
