### ISSUE TITLE
Unable to edit / remove team alias

### ISSUE THREAD

**Issue by aPatchyDev** [ctftime/ctftime.org#252]
I wanted to edit a team alias, but it ended up creating a new alias while the old one stayed, and it does not seem to be possible to remove an alias once it is made. Is there any workaround that does not reset the team record / members?

**Comment by 0xW00dy** [comment]
Hey, same issue here. As our team split I'd like to give back their alias to the leaving players. 
I would appreciate a workaround. 
Thanks

**Comment by emp4556** [comment]
up

**Comment by FireCC** [comment]
up

**Comment by Rustfy** [comment]
Hi,

Same thing with me, would like to remove some team name aliases, please any solution/workaround to such issue.

Thank you,

**Comment by kyprizel** [comment]
Sorry, should be fixed now.
