### ISSUE TITLE
Every action done on ctftime on my account give me "OK(not really you are acting as a spammer)"

### ISSUE THREAD

**Issue by TomiyokaGiyu** [ctftime/ctftime.org#258]
![Screenshot from 2022-02-17 09-44-58](https://user-images.githubusercontent.com/99639735/154405476-577339e4-0844-407c-b73b-4cab9e129c7b.png)
I can't even delete my account

**Comment by Hiteke** [comment]
me too

**Comment by kyprizel** [comment]
that means you're acting as spammers :)

**Comment by AlphaWHH** [comment]
I signed in with Github on the site and I did 3 actions (change timezone, try to join team and try to create team) and each time I got the same message.  Maybe some kind of message about too many actions but wanting to join a team or changing first and last name seem like common first actions. The message being triggered on changing profile information is tuned a little too aggressively.

The same message comes when I tried to leave feedback on the site. Every action I did gave the same message. It makes it feel like I am not able to use the site and that it is immediately hostile.

**Comment by x4132** [comment]
Also got this, literally can't do anything. Didn't even touch anything except for team join and contact info. Can't delete account, can't join a team, can't change contact info

**Comment by x4132** [comment]
Another note: it seems like almost all POST request data is being blocked. I can't even search for a team.

**Comment by kyprizel** [comment]
Clear your cookies.
