### ISSUE TITLE
merge team request is pending

### ISSUE THREAD

**Issue by jkjh0819** [ctftime/ctftime.org#273]
I requested merge as alias last week, but the request status is still pending.
- https://ctftime.org/team/141297
- https://ctftime.org/team/193902

I saw the FAQ about team merge. It said I can merge teams not later than 2 weeks after the event finished, so I make this issue. 

Could you check the request?

**Comment by daniel-vos** [comment]
We have the same problem (also for FAUST CTF 2022) because team names with spaces weren't allowed. Our teams are:
- TU Delft CTF Team: https://ctftime.org/team/134822
- TU_Delft_CTF_Team: https://ctftime.org/team/193900
