### ISSUE TITLE
The sum of the points is false

### ISSUE THREAD

**Issue by Leslato** [ctftime/ctftime.org#276]
The sum of the points obtained by our team "Flag Poisoning" is not the good one, we miss approximately 200.000 points, if possible could you arrange the issue.
Team Link: https://ctftime.org/team/175428

**Comment by XeR** [comment]
> [No matter how many CTFs your team participate - only 10 best results count in yearly rating.](https://ctftime.org/rating-formula/)

Your 10 best placements are :

```
  2   Digital Overdose Conference 2022 CTF  4100.0000   35.270
  4   Cyber Grabs CTF 0x03 Junior           6550.0000   29.038
  4   MidnightFlag - INFEKTION 2022         13909.0000  27.472
  8   SHELLCTF 2022                         5952.0000   26.730
  3   wtfctf 2022                           3169.0000   22.772
  4   hackrocks & HackArmour CTF            460.0000    22.358
  5   Incognito 3.0                         7276.0000   20.426
  13  TFC CTF 2022                          7368.0000   20.144
  18  UMDCTF 2022                           14571.0000  19.082
  17  JerseyCTF II                          8015.0000   18.288
```

The sum of these points is 241.580; 0.001 points away from your current score of 241.579. This happens because scores are rounded.
