### ISSUE TITLE
Spam

### ISSUE THREAD

**Issue by fl1k** [ctftime/ctftime.org#279]
I can't do shit on the site

'OK (not really, your are acting as a spammer)'

Very bad

**Comment by sgtpepper43** [comment]
Apparently you've gotta clear your cookies https://github.com/ctftime/ctftime.org/issues/258
At least it worked for me, anyway. I don't know why that issue is closed, it's clearly a bug 😂

**Comment by erin-bristow** [comment]
Argh same.

**Comment by NullBrunk** [comment]
Cleared my cookie, it worked

**Comment by iagox86** [comment]
Can confirm deleting cookies + logging back in works, but what a pain! Overly aggressive anti-spam
