### ISSUE TITLE
CTF Writeups "New Writeups" section on ctftime getting spammed

### ISSUE THREAD

**Issue by RDxR10** [ctftime/ctftime.org#283]
The writeup section on ctftime is getting flooded with random site links. Can the core team look into it?
Thanks

![writeup](https://user-images.githubusercontent.com/43957261/190888483-ba51e921-3970-41c3-8044-d6150f7c8b4f.PNG)

**Comment by kyprizel** [comment]
Thank you for the report.
I've tried to fix spam issues and some roots of the problem.
