### ISSUE TITLE
Wrong Max Point for ISITDTU Quals 2022

### ISSUE THREAD

**Issue by bvqhuynh** [ctftime/ctftime.org#284]
Hello, the max point for our event in 2021 is 34, but it still showing for us is 25. Could you fix also this please? The event is https://ctftime.org/event/1757
![image](https://user-images.githubusercontent.com/71119588/191166092-842ebabe-1a90-4ba8-918e-953606375ea3.png)

![image](https://user-images.githubusercontent.com/71119588/191166157-797d2197-ce11-4d70-ae81-24a930428d0f.png)

Thank you!

**Comment by kyprizel** [comment]
it was not approved yet
