### ISSUE TITLE
Want to change the time of N1CTF 2022

### ISSUE THREAD

**Issue by MrRtcl** [ctftime/ctftime.org#285]
I am the organizer of N1CTF 2022. For some reason, we want to change the time of the game from Saturday, 26 November 2022, 00:00 UTC — Monday, 28 November 2022, 00:00 UTC to Saturday, 19 Nov 2022, 00:00 UTC — Monday, 21 Nov 2022, 00:00 UTC.
You can contact us at root@nu1l.com, thank you very much and look forward to your reply

**Comment by kyprizel** [comment]
done
