### ISSUE TITLE
unicode characters in team description

### ISSUE THREAD

**Issue by crowell** [ctftime/ctftime.org#29]
how to reproduce:

make team description "HackersWhoBl🍁ze"

notice that everything gets cut off after the "l" in Blaze

**Comment by kyprizel** [comment]
which event? have you tried to rename a team?

**Comment by crowell** [comment]
team "hackerswhoblaze" i tried to change "Description" here
https://ctftime.org/team/17715/edit/

and it choked after that.

On Wed, Oct 21, 2015 at 7:04 PM, Eldar Zaitov <notifications@github.com>
wrote:

> which event? have you tried to rename a team?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ctftime/ctftime.org/issues/29#issuecomment-150048944>.
>



-- 
Jeff Crowell
https://github.com/crowell

**Comment by kyprizel** [comment]
Can you try now?

**Comment by kyprizel** [comment]
looks like fixed
