### ISSUE TITLE
BambiCTF #7 is on the 5th of November, is not publicly listed, and we have submitted it weeks ago

### ISSUE THREAD

**Issue by Trolldemorted** [ctftime/ctftime.org#290]
Did anything go wrong? We now have less than 2 weeks remaining

**Comment by Trolldemorted** [comment]
The CTF still hasn't been approved. @kyprizel could you approve it, or tell us why it was not approved? :)

**Comment by kyprizel** [comment]
There was no any information about the event. Now it has an URL - approved.
