### ISSUE TITLE
Unable to post writeup - Team field is empty

### ISSUE THREAD

**Issue by amelkiy** [ctftime/ctftime.org#302]
I created a team after participating in a CTF and I can manage the team, it appears on the CTF's list of teams and the CTF appears on my team page, but when I try to post a writeup the "Team" field in the form is empty and I cannot select any team

CTF: [Insomni'hack 2023](https://ctftime.org/event/1850)
Team: [U@A](https://ctftime.org/team/220094)
My username: [amelkiy](https://ctftime.org/user/15371)

Is there any way around this?
Thanks!

**Comment by kyprizel** [comment]
Has your team got any points?

**Comment by amelkiy** [comment]
Yeah, we got 1074 points and ranked 24 but we were one of only 3 teams who solved the challenge I want to post

**Comment by kyprizel** [comment]
Please, try now?

**Comment by amelkiy** [comment]
Awesome, it worked! Thank you!!

**Comment by TheColorman** [comment]
This issue is still happening to other teams and other CTFs, our team itunderground has gotten points for FE-CTF 2023 in CTFtime but cannot post writeups:
![image](https://github.com/ctftime/ctftime.org/assets/18369995/e38a4dda-321a-4c55-a2e3-6b9f4ea3ae11)
