### ISSUE TITLE
Need to re-upload scoreboard!

### ISSUE THREAD

**Issue by Arul-Sujith** [ctftime/ctftime.org#305]
https://ctftime.org/event/1904

The platform has edited some team names wrongly. Is there a way to upload it again? I cannot find the option.

**Comment by kyprizel** [comment]
No there is not.

**Comment by Arul-Sujith** [comment]
I am reaching out to you regarding an issue with the scoreboard that I
noticed recently. As per my observation, there seems to be a mistake in the
display of our team name.

Our actual team name is "Br0s_C0d3_;-)", but it was displayed as
"br0s_c0d3_" on the scoreboard. I have identified issue #304 on GitHub also
the same, and I believe it is affecting everyone on our team and also most
of the members who participated in the CTF.

I am writing to request your assistance in rectifying this mistake. If you
need any further proof or information from me, please do let me know. I
would be more than happy to provide you with whatever is necessary to
resolve this matter.

Thank you for your time and attention. I look forward to hearing back from
you soon.
