### ISSUE TITLE
provide additional means of authentication

### ISSUE THREAD

**Issue by freddyb** [ctftime/ctftime.org#31]
As likely all users of ctftime are security nerds, you must understand that a lot of your users are uncomfortable with sharing their google/github/twitter/etc. details with ctftime.

It would be great if you added means of authentication that do not expose data or even grant you privileges to the respective accounts.

**Comment by kyprizel** [comment]
for example? I'm not going to add username/password auth.

**Comment by lam0re** [comment]
What's wrong with username/password auth? I really dislike the current authentication as well.

**Comment by shaaati** [comment]
To be honest, I don't like the third party authentication either. Creating and keeping track of fake accounts is cumbersome and using your real accounts somehow feels wrong.
Just as @lam0re, I am living with the current situation, yet I am unhappy with it.
Whenever we get a team email for new members requesting to join the team I ignore it, thinking that someone else of the team will probably log in and manage it anyway.

**Comment by WGH-** [comment]
I don't feel comfortable relying on third parties. I relied on Yandex OpenID once. Guess what happened next.

**Comment by kyprizel** [comment]
Sorry, but one more password auth sux ;)
