### ISSUE TITLE
CTF event without ranking 

### ISSUE THREAD

**Issue by adminush** [ctftime/ctftime.org#311]
A very interesting CTF was held with good tasks and a large number of participants. However, she was not assigned a rating and there was not even a vote. The platform rules do not specify anything about this, it complies with the rules: https://ctftime.org/event/1873

You can counter with the fact that the organizers did not have events and they did not participate anywhere, however, there are similar competitions with a rating: https://ctftime.org/event/1903 or https://ctftime.org/event/1892

Is this a bug and how to understand if the rating is calculated for events?

**Comment by kyprizel** [comment]
It was marked as "casual" from the begining.
