### ISSUE TITLE
TBTL CTF 2023 Event Approval

### ISSUE THREAD

**Issue by ipaljak-tbtl** [ctftime/ctftime.org#313]
Hi, 

can you please approve our CTF event (https://ctftime.org/event/2002) as we are getting really close to its start.

Thank you.

**Comment by dsantl-tbtl** [comment]
I kindly request your assistance in expediting the approval process for our CTF (https://ctftime.org/event/2002) event.

**Comment by ipaljak-tbtl** [comment]
Thanks :smile:
