### ISSUE TITLE
Merging team problem 

### ISSUE THREAD

**Issue by lephuduc** [ctftime/ctftime.org#321]
Hi, I'm Jinn, called as `cuucon` on ctftime. I'm currently playing for `The Council of Sheep` https://ctftime.org/team/221828 and the problem is we're played `HCMUS CTF 2023 Qualifications` as team `Republica de Ricon` https://ctftime.org/team/226000. We have merge team request to `The Council of Sheep` alias as `Rep\xfablica de Ricon` but it still pending. Could you help me resolve it?

**Comment by rawad9** [comment]
We have the same problem!
