### ISSUE TITLE
Unblock request

### ISSUE THREAD

**Issue by xtexx** [ctftime/ctftime.org#325]
Hello,

My username is xtex. I wonder why it shows "OK (not really, your are acting as a spammer)" almost everywhere?
Maybe I did something wrong?

Thanks.

**Comment by maverickk89** [comment]
@kyprizel me too

**Comment by maverickk89** [comment]
I cannot open a ticket on the website because I got the same message

**Comment by e1c4mp3r0** [comment]
Hi @kyprizel, i'm having same issue. Could you please help on this?
<img width="590" alt="ctftime-spammer" src="https://github.com/ctftime/ctftime.org/assets/175165077/7a57dc28-8bd7-414e-ace3-1e5711ce23ff">
