### ISSUE TITLE
Team unaccessible after updating logo image

### ISSUE THREAD

**Issue by gum3t** [ctftime/ctftime.org#341]
Hello!
Last week I tried to change my ctf team logo and once I clicked on 'save', the team was no longer accessible (returns 404 after clicking on the team's name). I cannot see my team on the dropdown menu, however if I click to see my full profile, I can see the team.
The team appeared in the Spanish rankings for a few days more but its not there anymore.
My username is: Serrallonga
The team is called: Samfaina (https://ctftime.org/team/215458)
I can PM more info if necessary.

**Comment by kyprizel** [comment]
antispam decided teams description was too spam-like.
