### ISSUE TITLE
Minor typos on competition page

### ISSUE THREAD

**Issue by aspyatkin** [ctftime/ctftime.org#36]
Hello, I've spotted some minor typos on competition page (e.g. [this one](https://ctftime.org/event/279))

Typos are marked bold and possible corrections are marked italic:
1. **An** VolgaCTF Quals event (*A*) - however, it depends on the first letter of the event's title
2. **Offical** URL (*Official*)
3. This **events** weight (*event's*)

**Comment by kyprizel** [comment]
thanks, fixed.
