### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [ctftime/ctftime.org#366]
.

**Comment by andrewbae** [comment]
Additionally, I am attaching two photos to show that I am the owner of the account. I can receive your verification number via email.
<img width="1169" alt="Screenshot 2024-03-09 at 03 34 50" src="https://github.com/ctftime/ctftime.org/assets/161595118/2621dc06-abfe-45ed-8832-490ef85deaed">
<img width="1149" alt="Screenshot 2024-03-09 at 03 34 42" src="https://github.com/ctftime/ctftime.org/assets/161595118/34cadffc-938a-4361-b2f7-a0fb041bff47">
