### ISSUE TITLE
Allow reuploading of results for TexSAW 2024

### ISSUE THREAD

**Issue by treegwenn** [ctftime/ctftime.org#371]
Hello, we recently ran a CTF named [TexSAW2024](https://ctftime.org/event/2281) on March 23, 2024, and we made a mistake with the scoreboard as one of the teams on there included members who contributed to the CTF (conflict of interest). We would like to be able to reupload the scoreboard so it doesn't include this team. Can you make the results editable to the organizer of the event (UTD TexSAW)?

Thank you!

**Comment by kyprizel** [comment]
Try now

**Comment by treegwenn** [comment]
Is the button to reupload supposed to be visible on the page https://ctftime.org/event/2281/result ? I have looked around at that page and other pages, but do not see the button to upload another result file. Attached are the screenshots of what I see on the top and bottom of the results page for TexSAW2024.

![ctftime1](https://github.com/ctftime/ctftime.org/assets/165737415/be17f5d2-dfe7-4028-9abb-612392c2c35a)
![ctftime2](https://github.com/ctftime/ctftime.org/assets/165737415/d5a6916a-06cd-43e1-9b37-2459fad2c6dc)

**Comment by kyprizel** [comment]
and now?

**Comment by treegwenn** [comment]
Works, thank you!

**Comment by treegwenn** [comment]
reuploaded results.
