### ISSUE TITLE
`social_auth_usersocialauth` crashed

### ISSUE THREAD

**Issue by mbiesiad** [ctftime/ctftime.org#374]
Hi,

**Repro steps:**
Go to https://ctftime.org/ click Sign in (top right) and select Twitter icon https://ctftime.org/login/twitter/?next=/
After redirections https://ctftime.org/login/ see error `(145, "Table './ctftime/social_auth_usersocialauth' is marked as crashed and should be repaired")` - can't be logged in.

**Screenshot:**
![err](https://github.com/ctftime/ctftime.org/assets/18367606/866dcbb1-d5e2-4985-9916-6a7ca77765f2)

**Additional informations:**
Yesterday (2024-4-6) it worked properly.

Best wishes,

**Comment by Shoot** [comment]
Same

**Comment by modular0558** [comment]
Same issue here. Can't login using any of those services

**Comment by Shoot** [comment]
Fixed!

**Comment by mbiesiad** [comment]
Right, really quick reaction. Cool 🚀 All is fine now 🎉
