### ISSUE TITLE
'Upcoming' events filter by location (online/on site) and 'Notes' (all/academic only)

### ISSUE THREAD

**Issue by bl4de** [ctftime/ctftime.org#39]
There's a list of upcoming events here:

https://ctftime.org/event/list/upcoming

Filter criteria right now allows to filter events by format and year.
It would be nice to add 'Location' filter (online/on site) and 'Notes' (open for all teams/schools only/invites only)

**Comment by kyprizel** [comment]
Done (alpha version):
https://ctftime.org/event/list/upcoming

**Comment by bl4de** [comment]
Awesome, now it's even better than in my proposition, thanks :)

> I really appreciate @kyprizel work with ctftime.org website and I see totally lack of interests in helping him with this. Forgive me @kyprizel, but now, ctftime.org from UI/UX point of view is a crap.
I've opened an issue in May 2016 about some improvement:
#39
There's no comment there. Even one. And no doubt filtering events on ctftime.org needs to improve its usability.

I just want to show them all, that nobody cares about your work.
But as you can see in #40 discussion, they did not notice my comment at all.
