### ISSUE TITLE
Not able to join the team as a first member.

### ISSUE THREAD

**Issue by Rembo-FW** [ctftime/ctftime.org#392]
Team url: https://ctftime.org/team/277323
Nickname on ctftime: MindBreakers_Admin

I'm the captain of the ESGI team and I cannot join, even though I'm the first one. The team was autocreated years ago when we participated in [HTB University CTF 2023: Brains & Bytes](https://ctftime.org/event/2149).

Yes, that's a school team, and i'm a teacher of this school, so i need to join for manage student

**Comment by Rembo-FW** [comment]
Same for the team nickname ESGI https://ctftime.org/team/3151

**Comment by thxStuck** [comment]
+Я так же не могу присоединиться к своей команде, хотя у меня есть сертификаты победителей с наших CTF
![image](https://github.com/ctftime/ctftime.org/assets/160881462/b5773941-8006-4515-8ae8-d0ae84cd3a40)

https://ctftime.org/team/223931
Мой аккаунт на вашей платформе - thxStuck. Этот гитхаб там указан как web site

**Comment by Zwique** [comment]
Same for the team Que
Username: Zwique
https://ctftime.org/team/61346

**Comment by syselement** [comment]
Same for team **martialHack**
https://ctftime.org/team/200707

Username: **syselement**

![image](https://github.com/ctftime/ctftime.org/assets/81392234/bd5c35b5-684a-4be0-98cc-13e784f6c320)

HackTheBox CTF Webpage - where I created the team
![image](https://github.com/ctftime/ctftime.org/assets/81392234/29942479-c4dd-4d2c-8b30-d7f216bbf744)

**Comment by Rembo-FW** [comment]
It's good for me thanks
