### ISSUE TITLE
Whitelist enowars8 portal for oauth2 token endpoint (https://oauth.ctftime.org/token)

### ISSUE THREAD

**Issue by Trolldemorted** [ctftime/ctftime.org#394]
Hey,

could you add `49.13.215.165` to your cloudflare whitelist like last year (https://github.com/ctftime/ctftime.org/issues/326)?

Thanks in advance, keep up the good work!

**Comment by kyprizel** [comment]
try now?

**Comment by Trolldemorted** [comment]
So far it works, should we get 403s I'll reach out ❤
