### ISSUE TITLE
Request for join team as first member

### ISSUE THREAD

**Issue by hlc23** [ctftime/ctftime.org#411]
Username: `hlc23`
Team: [`hlc23`](https://ctftime.org/team/301718)

**Comment by 0x8j0rn4r80r93** [comment]
@hlc23 did you solve this? Having the same issue myself but have not created a issue here on Github yet. Have sent them a e-mail only.

**Comment by hlc23** [comment]
Yes. they put me into the team after open issue about one or two day. Maybe you can try  issue or wait for mail response.

**Comment by 0x8j0rn4r80r93** [comment]
Thank you for the reply!
