### ISSUE TITLE
Impossible to comment on CTFs

### ISSUE THREAD

**Issue by MathisHammel** [ctftime/ctftime.org#42]
<img width="559" alt="screen shot 2017-02-15 at 4 06 57 pm" src="https://cloud.githubusercontent.com/assets/6159437/22983138/164157f4-f399-11e6-99dc-bad90ad6522d.png">

The issue happens 100% of the time to me. Ways to reproduce the issue:

- Click on a CTF
- Type comment
- Click 'send'

In case the issue is inconsistently reproducible on other profiles, my user id is 14986

**Comment by kyprizel** [comment]
CTF or Event? Can you provide a link?

**Comment by kara71** [comment]
I did not know there was a difference. It happens on https://ctftime.org/event/367 for example

**Comment by kyprizel** [comment]
That's b/c you don't have email in your profile.

**Comment by kara71** [comment]
I saw that earlier too, can't edit my profile without putting my email in there. Maybe update the error message to be more helpful ?

**Comment by kyprizel** [comment]
Thanks, fixed.
