### ISSUE TITLE
[Bug] Inactive Team with no members left; cannot join nor use its name

### ISSUE THREAD

**Issue by stanley0010** [ctftime/ctftime.org#421]
My team would like to use the name "Nightwing", but it has been taken. See https://ctftime.org/team/86805.
However, the team has been inactive since 2021, and now has no members.

![image](https://github.com/user-attachments/assets/d24d56b3-1ce5-489e-a49c-f89c39bb248d)

I tried clicking "I'm in the team!". But I think the invitation request is sent to no one. Right now, my request status is "pending". What can I do other than using another name? I hope I can claim the team name. Thanks!

**Comment by daystudio** [comment]
I am in same team as @stanley0010 wrote above.  We have completed a recent CTF competition and get into the finalists.   The official organizer of the event request us to confirm the name ASAP, but we have to align our name with our record on ctftimes.  Please confirm this issue asap.  Thx.

**Comment by kyprizel** [comment]
Some team memberships can be confirmed earlier than another, but there is a problem - I can not read your minds ;) (providing team names helps).
Also, it is recommended to create teams at CTFtime _before_ the competition so team membership will not be a problem.

**Comment by stanley0010** [comment]
> Some team memberships can be confirmed earlier than another, but there is a problem - I can read your minds ;) (providing team names helps).
> 
> Also, it is recommended to create teams at CTFtime _before_ the competition so team membership will not be a problem.

Thanks for the reply. We can now join the NightWing team although the past CTF records of the team are still here (2019-2021). I have submitted another ticket for this on CTFTime. Thanks!
