### ISSUE TITLE
Main ranking doesn't seem to refresh/recalculate

### ISSUE THREAD

**Issue by gynvael** [ctftime/ctftime.org#45]
Hi,

Mostly about https://ctftime.org/event/383:

  * I don't think it's calculated into the ranking score (i.e. DS' best 10 scores sums to ~260, but it's at 176pts now)
  * Future weight is 0, even though the voting has ended and it should be way more than 0.

Worth looking into :)

**Comment by kotobukki** [comment]
All of the latest event is also like that

**Comment by kyprizel** [comment]
Sorry, looks like I broke the stuff right before going to vacation :(
Should be fixed now - please check.

As a side effect iCTF 2017 weight was changed from 0 to 25.

**Comment by gynvael** [comment]
Thanks!
