### ISSUE TITLE
The contest organizer cannot change the duration.

### ISSUE THREAD

**Issue by nomeaning777** [ctftime/ctftime.org#46]
It is impossible to modify the contest duration even by the contest organizer.   

We can set the duration of new contest. (at https://ctftime.org/event/new https://ctftime.org/event/mail )
However, the duration of created event is sometimes not correct. For example, we organized three contests and we input correct duration in UTC(at least two contests), but all of the first duration has an error.

Therefore, it is good that the contest organizer can change the duration at https://ctftime.org/ctf/{id}/edit/.

**Comment by kyprizel** [comment]
It's intentional. Please, check times twice.
