### ISSUE TITLE
adding event tasks fails

### ISSUE THREAD

**Issue by noraj1337** [ctftime/ctftime.org#49]
Since about 1 week, adding event tasks fails for every CTF (finished ones, some recently, some a long time ago). It's normal to get 404 error when adding tasks for future or running CTF but it's not normal to get error 500 for past event.

For example I get this error when trying to reach https://ctftime.org/tasks/451/new/ :

![](http://i.imgur.com/dXxz3eB.png)

**Comment by kyprizel** [comment]
Please, check now?

**Comment by noraj1337** [comment]
@kyprizel Works now. It occurs times to times. Do you know why?

**Comment by kyprizel** [comment]
Should be fixed now (I patched before asking you to check).
