### ISSUE TITLE
Displayed event weight should come from "rating weight" and not "future weight"

### ISSUE THREAD

**Issue by Pharisaeus** [ctftime/ctftime.org#51]
I just noticed that there seems to be an issue with the current/future weight displayed for some events. Let's look for example at https://ctftime.org/event/433
There is:
```
Future weight: 25.00 
Rating weight: 10.00 
```
Which is ok, and the 1st team got 20 pts.

But if we look at event history page https://ctftime.org/ctf/103 the we have
```
Teaser CONFidence CTF 2017	25.00
```

And the same if we go to Dragon Sector profile https://ctftime.org/team/3329 there is:
```
Teaser CONFidence CTF 2017	25.00
```

Nonetheless, the point calculation is fine because it's easy to see that Dragon Sector actually got 20 pts for organizing the event, so it's just the displayed value which is wrong.

**Comment by kyprizel** [comment]
Teaser CONFidence CTF 2016 had weight 10.

**Comment by Pharisaeus** [comment]
I know, and the calculations are fine. But when you go into the links I provided and look at what is displayed for Teaser CONFidence CTF 2017 weight it shows 25, even though 25 is the estimated "next year" (aka 2018) weight and this year the weight is still 10.
This means CTFtime shows "next year weight" / "voting result" instead of the actual weight for the event.

**Comment by kyprizel** [comment]
Is it ok now?

**Comment by Pharisaeus** [comment]
@kyprizel if you follow the links I provided it's clear that nothing has changed for them, there is still some confusion between current and next rating. Just to recap:

1. https://ctftime.org/event/433 shows that rating was `10` and next year rating going to be `25`, and the winning team got `20 points`, so this is correct.
2. https://ctftime.org/ctf/103 shows that rating of this event was `25` instead of the correct value of `10`, so this page shows most likely the "next year rating" instead of "current rating"
3. https://ctftime.org/team/3329 similarly shows event rating of `25` instead of `10`

It's not an issue of actual score calculation, but only that incorrect value is displayed in the event details page and organizing team page.

**Comment by kyprizel** [comment]
Ah, see it now. Thanks - fixed!
