### ISSUE TITLE
cant delete team members

### ISSUE THREAD

**Issue by securisec** [ctftime/ctftime.org#54]
getting this error when trying to delete team members. 

There was an error while removing member from the team: max_value,min_value,required,invalid

**Comment by abdilahrf** [comment]
same here 
this is why my team name become this cool emoji, because i can't leave the team hahaha

![image](https://user-images.githubusercontent.com/6015012/30522352-e3e494f2-9bf8-11e7-8fa1-3e3b2b870687.png)
