### ISSUE TITLE
Type in hover text of question mark near 'Future weight' in CTFs

### ISSUE THREAD

**Issue by zootos** [ctftime/ctftime.org#55]
When hovering the question mark for 'Future weight' for a given CTF, the text reads 'This weigt will be used in next years rating', while it should read 'This weight will be used in next years rating'

![image](https://user-images.githubusercontent.com/10966505/29494661-83580196-85af-11e7-85db-be79db21194f.png)

**Comment by kyprizel** [comment]
Thanks
