### ISSUE TITLE
"Overall rating place" vs "position" discrepancy?

### ISSUE THREAD

**Issue by 0xd13a** [ctftime/ctftime.org#59]
Hi, I noticed that "overall rating place" in the team page and the position in the main team list differ significantly for many teams. For example Dragon Sector and LC/BC are currently in positions 3 and 4:
 
![ctftime](https://user-images.githubusercontent.com/23625470/33146394-f6c8fd8e-cf91-11e7-9b3a-333660c17579.png)

...and at the same time their overall rating places are 7 and 3, respectively:

Dragon Sector: "Overall rating place: 7 with 500.585 pts in 2017"
LC/BC: "Overall rating place: 3 with 522.735 pts in 2017"

If this is not a bug can you please add a note to [https://ctftime.org/rating-formula/](https://ctftime.org/rating-formula/) to explain the way positions are calculated? 

Thanks!

**Comment by kyprizel** [comment]
Sorry, that was a caching issue. Should be fixed now.

**Comment by 0xd13a** [comment]
Thanks! https://ctftime.org/stats/2017 now gives a 500 error...
