### ISSUE TITLE
API is down

### ISSUE THREAD

**Issue by MathisHammel** [ctftime/ctftime.org#60]
All API endpoints as listed on https://ctftime.org/api/ are 404.
If that can be of any help to find the root cause, the last successful call on our side was on 2017-12-10 14:18 UTC (we call the API every 72h).

**Comment by kyprizel** [comment]
Hi,
can you please describe briefly how do you use the API?

**Comment by MathisHammel** [comment]
We have a Slack bot reminding us of upcoming CTFs : https://github.com/HugoDelval/flagbot
(dirty code warning)

**Comment by noraj** [comment]
https://ctftime.org/api/v1/teams/ works
but
https://ctftime.org/api/v1/teams/{team_id}/ is not

**Comment by noraj** [comment]
Also the link is broken on CTFtime.org because `href` is miss spelled ![](https://i.imgur.com/nmwtUGp.png)

**Comment by kyprizel** [comment]
Should be fixed now.

**Comment by noraj** [comment]
@kyprizel Works fine now, awesome :)
