### ISSUE TITLE
CTF weight is always 0.0 on RSS feed

### ISSUE THREAD

**Issue by Nhoya** [ctftime/ctftime.org#63]
Every time a CTF is announced the weight on the RSS is always 0.0

**Comment by s0h3ck** [comment]
This issue is reflected on the API as well. Any updates?

**Comment by kyprizel** [comment]
Can you please provide an example?

**Comment by s0h3ck** [comment]
> Can you please provide an example?

Of course! Open your terminal and run the following commands:

```bash
result="$(curl -s "https://ctftime.org/api/v1/events/?limit=100")"
echo $result
```

The result is [here](https://pastebin.com/Bgc6C9mN). Then, you compare with the upcoming CTF events on [ctftime](https://ctftime.org/event/list/upcoming). Image below :

![1555800089](https://user-images.githubusercontent.com/7539558/56463110-f56aab00-639b-11e9-8139-5176f1d3bd65.png)

You see, CTF weight is always 0.00 from the API or the RSS feed (according to @Nhoya).

Here is the rest of the commands to view the result in the terminal :

```bash
readarray -t weight_array <<< $( echo $result | grep -Po '"weight":.*?[^\\],' | cut -c11- | rev | cut -c2- | rev)
echo "${weight_array[*]}"

0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
```
All zeros ;)

**Comment by kyprizel** [comment]
Fixed, thanks!
