### ISSUE TITLE
Creator of group can't edit details because the group is less than 7 days old

### ISSUE THREAD

**Issue by JuanPotato** [ctftime/ctftime.org#64]
![image](https://user-images.githubusercontent.com/9531780/36237469-dd86bda0-11c9-11e8-9219-713cf9010b3a.png)

I get this when I try to add a group photo because the group hasn't existed for seven days yet even though I was the creator. Sounds like a bug.

**Comment by kyprizel** [comment]
I was  tired of spammers and added this limit. Reduced this to 1 day.
