### ISSUE TITLE
Cant change my teams' country to Turkey

### ISSUE THREAD

**Issue by frkntrn** [ctftime/ctftime.org#66]
I can change my teams' country to any country, but Turkey. Why?

**Comment by kyprizel** [comment]
There is a person from Turkey hijacking unclaimed teams.
https://twitter.com/AtAvratPwn/status/954757854640078848
Some team claiming limitations were added to prevent this.

**Comment by frkntrn** [comment]
How can i change it though, I am from Turkey. At the beginning, my teams' country was Turkey. But at that time I couldnt change other settings. So I changed the country but now I am not able to change it again :)

**Comment by kyprizel** [comment]
There is a description of limit.

**Comment by frkntrn** [comment]
But i can change my other teams country to Turkey.
