### ISSUE TITLE
Writeups duplicated

### ISSUE THREAD

**Issue by 0xd13a** [ctftime/ctftime.org#67]
I was adding my writeups, and after submitting the text I clicked one of the breadcrumb links (I think it was "Writeup"). That caused the writeup to be submitted twice:

https://ctftime.org/task/5644
https://ctftime.org/task/5612

Please remove the duplicates (and fix the underlying problem, if it's an actual bug). Thanks!

(Update: my mouse if malfunctioning and sometimes sends 2 clicks instead of 1. There is a possibility that it sent 2 clicks for the Submit button in quick succession, and that led to double writeup submission. Still, it would be better to prevent that.)

**Comment by kyprizel** [comment]
Thanks, i'll think about dublicate prevention.
