### ISSUE TITLE
Refresh issues when posting writeups

### ISSUE THREAD

**Issue by 0xd13a** [ctftime/ctftime.org#68]
When creating a new writeup and posting large text a screen refresh is needed. This occurs on Chrome, may be possible with other browsers. This is a minor UI bug.

To reproduce:

* Start a new writeup
* Post a text that is a few pages long into the Writeup window
* Scroll the window up and you will see that the top part of your text is missing
* Click inside the empty space to get the text to re-appear

**Comment by kyprizel** [comment]
Can you check now?

**Comment by 0xd13a** [comment]
Looks like it's working - thanks!
