### ISSUE TITLE
Can't submit scoreboard

### ISSUE THREAD

**Issue by ehennenfent** [ctftime/ctftime.org#69]
UIUCTF 2018 had a live scoreboard up at  [this address](https://uiuc.tf/contests/uiuctf-2018.json) for the duration of the competition. Unfortunately, our scores never got parsed into the ctftime site. Submitting them manually does not seem to work either - while the interface says they were submitted successfully, no data shows up on the main page.

We've confirmed that our endpoint emits valid JSON, and as far as we can remember, everything worked just fine for UIUCTF 2017 last year. Not sure what's going on now, but it seems like something must be silently failing on the ctftime backend.

**Comment by kyprizel** [comment]
Scoreboards are approved manually.
