### ISSUE TITLE
Team merge issue

### ISSUE THREAD

**Issue by fortenforge** [ctftime/ctftime.org#70]
I would like to merge 'galhacktictrendsetters' into 'galhacktic trendsetters', but the automated form won't let me.

**Comment by wangray** [comment]
Bump @kyprizel

**Comment by kyprizel** [comment]
join the teams.

**Comment by wangray** [comment]
Can you join the teams for us? The [merge form](https://ctftime.org/team/merge/) is giving the error "You can't merge teams participated in events later than 2 weeks after the event ends".

The teams are https://ctftime.org/team/27939 and https://ctftime.org/team/29927

Thanks.

**Comment by kyprizel** [comment]
No I can't.

**Comment by wangray** [comment]
Hi @kyprizel, can you please delete our team that we have been unable to merge? https://ctftime.org/team/29927

We would like to have it deleted so that we can add the name as an alias to our original team.
