### ISSUE TITLE
Time zone conversion error

### ISSUE THREAD

**Issue by jowabels** [ctftime/ctftime.org#72]
There seems to be an error with the time zone conversion. For example, the official website of TJCTF 2018 event states that the CTF schedule will be:

> 7:00 PM EDT on August 6, 2018 to 7:00 PM EDT on August 12, 2018

However, at the ctftime.org website, the local conversion of the time (PHT in my case), states the following as the schedule:

> Tue, 07 Aug. 2018, 03:00 PHT — Mon, 13 Aug. 2018, 03:00 PHT

PHT is 12 hours ahead of EDT, thus the correct schedule that should be shown in the ctftime.org website should be:

> Tue, 07 Aug. 2018, **07:00** PHT — Mon, 13 Aug. 2018, **07:00** PHT

**Comment by kyprizel** [comment]
That's b/c organizers ignored requirement to send event date in UTC.
