### ISSUE TITLE
Ics file problem

### ISSUE THREAD

**Issue by tamasbakos** [ctftime/ctftime.org#75]
Hi,
I'm having a problem with the .ics calendar file that can be downloaded for each CTF. If I try to open it with Google Calendar (Android 8.1), it says "unable to launch event". 
According to this https://stackoverflow.com/a/50086343 , a property named DTSTAMP is missing.
Could you please correct this, so it works without problems on Android?
Thanks, have a nice day

**Comment by kyprizel** [comment]
Please, check now?

**Comment by tamasbakos** [comment]
It works now, thanks. The title also appears in the notes though
