### ISSUE TITLE
[Enhancement] displaying unrated WU

### ISSUE THREAD

**Issue by noraj** [ctftime/ctftime.org#76]
Display something like *not noted yet* or *no rating*; etc. instead of `0` when a WU has not been rated yet.
Else it looks like it is a low quality WU.

**Comment by kyprizel** [comment]
Thanks, fixed.

**Comment by noraj** [comment]
The fix is not live yet ?

![image](https://user-images.githubusercontent.com/16578570/56390803-28daf780-622d-11e9-8f04-5ba1b8e3c97d.png)

**Comment by kyprizel** [comment]
Ah, that's what you talking about!

**Comment by noraj** [comment]
@kyprizel Yes, what did you change so?

**Comment by kyprizel** [comment]
Fixed, thanks.
