### ISSUE TITLE
Open-source the website

### ISSUE THREAD

**Issue by Aurel300** [ctftime/ctftime.org#77]
I don't know if this has been suggested before, but I didn't see it in the issues here. I understand that the author / host may want to keep control of the website but the source could still be available and accept pull requests. I would be happy to contribute but I cannot. Personally I think the website is starting to appear a bit dated, and some common tasks are a bit painful. For me, a shortlist is:

 - Orgs should be able to provide a canonical task list with points
 - If the task list is not provided, there should be some way to (vote to) merge duplicate tasks in the list
 - Easier access to my teams (instead of having to go through profile)
 - Non-social network login methods
 - Notifications for write-up comments
 - API for write-ups, since copy-pasting dozens of write-ups could easily be automated

**Comment by SakiiR** [comment]
THAT WOULD BE GREAT AS ****

**Comment by manuelvsousa** [comment]
Can we get any feedback from the current maintainers on this? @kyprizel

**Comment by kyprizel** [comment]
No, we're not going to opensource the website at the moment.
