### ISSUE TITLE
Suggestion: Participants improvement

### ISSUE THREAD

**Issue by Mizari** [ctftime/ctftime.org#81]
Hello. I suggest to sort upcoming CTF participants by their current rank and cut to limited amount by default (expandable). This makes participants part to be more relevant. Currently nobody actually uses it, since if you do, then your team will just disappear in some spam-teams, that usually do not even register in CTF itself.

**Comment by Pharisaeus** [comment]
Is there even a point in using this feature? There are no notifications attached to it, and it literally does nothing.

**Comment by kyprizel** [comment]
Actually now it's used for Telegram notifications. Also it can be useful to organizers how many teams to expect.
One day, may be, it'll automatically add qualified teams to final events (not sure how to correctly implement it yet).

**Comment by kyprizel** [comment]
I like the idea of limiting items in a table (looking for a bootstrap/jquery ninja to implement it).

**Comment by kyprizel** [comment]
I added planned events to a team page, may be now with oauth it can be useful.
