### ISSUE TITLE
disable captcha

### ISSUE THREAD

**Issue by noraj** [ctftime/ctftime.org#84]
Why captcha for authenticated users? This make publishing a nightmare.

**Comment by kyprizel** [comment]
On which page (action)?

**Comment by noraj** [comment]
Submitting a WU.

**Comment by noraj** [comment]
Or please go for reCaptchav3

**Comment by kyprizel** [comment]
Thank you. Fixed.

**Comment by XeR** [comment]
> reCaptcha score is too low. score: %(score)s

I can't submit writeups anymore.
Can we go back to the previous captcha ? Clicking images was a chore but it did not question my humanity.

**Comment by kyprizel** [comment]
Which score do you get?

**Comment by XeR** [comment]
> Which score do you get?

I do not know. The error message says that I have a score of `%(score)s`. It might be a bug.

I managed to get around by randomly clicking stuff on the website. It appear to have raised my score enough to post writeups. Not sure if everyone would have the patience to do that...

Requiring captchas for users who wrote less than n writeups seems like a good compromise.

**Comment by kyprizel** [comment]
I decreased the required ratio. Nice idea about writeups count!
