### ISSUE TITLE
500 error on profil

### ISSUE THREAD

**Issue by bali0x4d** [ctftime/ctftime.org#86]
Hello , i'have 500 internal error when i tried to reach my profil page or dating page. 
Is it normal ?
Thanks in advance.

**Comment by kyprizel** [comment]
Did you use github for logon?

**Comment by bali0x4d** [comment]
yes i'm using github for login.

**Comment by kyprizel** [comment]
Try now.

**Comment by bali0x4d** [comment]
it's working , thks a lot.
