### ISSUE TITLE
Suggestion: Improve Former/Rejected Section

### ISSUE THREAD

**Issue by UTCoordinator** [ctftime/ctftime.org#90]
Hello,

So, currently in CTFTime there is no way to know which members are former of a team or which ones are rejected. All of them go to the same tab namely `Former/Rejected`. I think that is very ambiguous because most top rated teams do get membership requests from dozens of new applicants and admins neither accept nor reject and keep it as it is -- just to not clutter their `Former/Rejected` section.

Also, considering a CTF player who served the team for many years and then he is removed from the team. Then he also goes under `Former/Rejected` section but any third party cannot distinguish between whether that person was indeed a member of that team (i.e Approved member) before or he was just another applicant who tried to apply that team and got rejected.

This being said, it becomes very hard to prove whether you were rejected or a veteran of that CTF team. 

So, my suggestion is this:
Rename the section `Former/Rejected` to only `Former` 
Those members who are *Approved* first and then removed, goes into that section
Those members who apply newly to a team and gets rejected before accepted are not logged anywhere. 

So what I propose is to remove the `Rejected` part completely. Don't make it public at all or clutter the former members who have served their team. That would look less respectful.

**Comment by kyprizel** [comment]
Good point - split the Former and Rejected. Currently I want to leave "Rejected" to be public so people can see who sends mass team membership requests.

**Comment by UTCoordinator** [comment]
Great @kyprizel . New layout is perfect.
