### ISSUE TITLE
Make the team name in the user dropdown menu link to the team page

### ISSUE THREAD

**Issue by FredrikAugust** [ctftime/ctftime.org#91]
As of now, when you click your team name in the dropdown menu which is shown upon clicking the name of your account, you are directed to the "Edit Team" page. I think it would be a lot more useful and intuitive if it redirected to the "Show Team" page instead. E.g. `/team/75672` instead of `/team/75672/edit`.

**Comment by UTCoordinator** [comment]
Good Point. I would think that even if they implement something as such known as a page which looks something like after you click on the team name on dropdown menu

```
[Edit XYZ Team]       [View XYZ Team]
```

So, in this case, after clicking XYZ from dropdown, it redirects to `/team/75672/options` which has two hyperlinks namely `/team/75672/edit` and `/team/75672`. 

That can be more elegant design but will require an extra management page -- but it will be scalable as you can add much more options later on in it.

**Comment by FredrikAugust** [comment]
Personally, I'd prefer just redirecting to the team page if you click the team name. It's just one click away to edit the team from there if needed, and it's not very often that you need to do that.

**Comment by kyprizel** [comment]
Thanks. Changed link to team page and it already has link to team management page.
