### ISSUE TITLE
Question about AngstromCTF

### ISSUE THREAD

**Issue by disconnect3d** [ctftime/ctftime.org#93]
Hey,

We could see in the past that certain CTFs got their weight changed to 0, even if they had a public voting - for example TAMUctf 19:
- https://ctftime.org/event/740
- https://webcache.googleusercontent.com/search?q=cache:ki5e6adr47oJ:https://ctftime.org/event/740+&cd=1&hl=pl&ct=clnk&gl=pl

EDIT: related issue - https://github.com/ctftime/ctftime.org/issues/94

It seems  this is mostly (or only) for CTFs that were "only for high school/academics" but I am not sure if the label saying the CTF will not be ranked was always there. 

My question is - is AngstromCTF (https://ctftime.org/event/774) going to be ranked? It says it is "Geared primarily towards high school students" but this doesn't exclude others.

Thanks,
Disconnect3d

**Comment by kyprizel** [comment]
This restriction was always used for events with restrictions. So if AngstromCTF is high-school only it's global weight is 0.

**Comment by kmh11** [comment]
I'm an organizer. We are not high school only for participation/rankings (just prizes), and do not currently have the restriction on CTFTime, so assuming it is not put there in the future, we should be fine and this issue can be closed.

**Comment by disconnect3d** [comment]
@kmh11 Thanks for making it clear. I am closing the issue! :)
