### ISSUE TITLE
TAMUctf 19 Marked as Academic Teams Only

### ISSUE THREAD

**Issue by ameserole** [ctftime/ctftime.org#94]
Howdy,

I am one of the maintainers of TAMUctf. I noticed that our public rating got dropped to zero points for TAMUctf 19 (https://ctftime.org/event/740). I've been told it's because it was marked as being for academic teams only. However, TAMUctf is not restricted to academic teams only and is open to everyone. It's just the challenge difficulty itself that is geared more towards university students. I also noticed that last years event got marked as academic only as well but it looks like the public rating wasn't dropped then (https://ctftime.org/event/559).

Would it be possible to have the academic teams only restriction removed and our public ranting restored?

**Comment by kyprizel** [comment]
Restriction removed, rating will be recounted automatically.
