### ISSUE TITLE
Now Running Section

### ISSUE THREAD

**Issue by kmh11** [ctftime/ctftime.org#95]
How is it determined which events are listed in the now running section? I am an organizer of angstromCTF, and although we are currently running, we are not listed there. The only thing I can think of is it's due to our slightly longer time frame (7 days), athough it's not like we go on for weeks and would clog up the section on the site.

If it is due to the long timeframe and you want to keep 7 days as not showing up, would we should up when there was less time left in the CTF?

**Comment by kyprizel** [comment]
Yes, CTFs longer than 5 days not listed.

**Comment by kmh11** [comment]
Hi,

In that case can we have the CTF modified to start on the 22nd at 00:00 UTC?

Thanks!

**Comment by kyprizel** [comment]
No you can't b/c CTF is actually already in progress and changing dates at CTFtime means nothing.

**Comment by kmh11** [comment]
Ah, I see. In this case we will just end the CTF at 00:00 UTC on the 25th (we will submit the scoreboard as of that time, but note that challenges will be left up as with past years of angstromCTF as well). Could we get the end date changed? We will make announcements once it's confirmed the end date on CTF Time will be changed.

Thank you.

**Comment by kyprizel** [comment]
Actually it was < 5 days, but Ok, changed.
