### ISSUE TITLE
ctftime.org is down?!

### ISSUE THREAD

**Issue by thecotne** [ctftime/ctftime.org#96]
- https://downforeveryoneorjustme.com/ctftime.org
 - https://www.isitdownrightnow.com/ctftime.org.html

<img width="543" alt="Screenshot 2019-04-24 19 43 45" src="https://user-images.githubusercontent.com/1606993/56673409-48f53580-66c9-11e9-8fc9-bc114ee1b0e1.png">

<img width="662" alt="Screenshot 2019-04-24 19 44 02" src="https://user-images.githubusercontent.com/1606993/56673436-514d7080-66c9-11e9-8255-ef24bb097a6b.png">

**Comment by kyprizel** [comment]
Well, sometimes we're being ddosed by impatient users. Need a hosting with more resources.
Should be fixed now.

**Comment by ahmedselim2017** [comment]
It is down again...

**Comment by kyprizel** [comment]
Network is being ddosed.
