### ISSUE TITLE
How to claim a team.

### ISSUE THREAD

**Issue by RahZelda** [ctftime/ctftime.org#97]
When I create a team, we find our team is already exists. But team status is pending. There is no one in the team, so that I can't join the team. I want to know how to claim a exists team.

**Comment by xlyker0p** [comment]
Any tip for this? - Thank you

**Comment by Samik081** [comment]
Same issue here

#Edit: after few days request got accepted :)

**Comment by 2kofawsome** [comment]
Its been over a week and Im still not accepted, anyone have any ideas?

**Comment by paulll** [comment]
Same issue here, and its been over a month
Team: `cpls`

**Comment by okisker** [comment]
I'm having the same issue

**Comment by kyprizel** [comment]
Create teams _before_ the event.

**Comment by 0xZ15H4N** [comment]
when i tried to register our team on ctf time , it told me that the team name is already register but there is no one on the team 
also we have played couple of ctf before with the same and those ctf have uploaded the rating too on the ctf time so our team get featured there as a team name no i can claim the team and points our team earned is there any way we can claim our team name back
