### ISSUE TITLE
Merge team names on CTFTime.org

### ISSUE THREAD

**Issue by theqlabs** [ctftime/ctftime.org#98]
We have used two different team names since "Cult of the Dead Squirrel" is too lengthy for some CTFs, we tend to use "cDs" as well. Both are registered: 

https://ctftime.org/team/75952 (Cult of the Dead Squirrel)
and
https://ctftime.org/team/43880 (cDs) 

Can you merge "cDs" as an alias to "Cult of the Dead Squirrel" ? 

We're most likely going to have to use both due to some CTF input restrictions.

Thanks <3

**Comment by kyprizel** [comment]
Please, use merge button on the site.
